In [ ]:
#pandas : python 의 data analysis의 핵심 library
#pandas는 고유하게 정의된 두개의 자료구조 이용
#series: numpy의 1차원 배열과 유사
#같은 데이터 타입을 가짐
#dataframe : numpy의 2차원 배열과 유사



In [25]:
import numpy as np

import pandas as pd

arr=np.array([-1,5,10,99])
print(arr)

print(arr.dtype)


arr2=np.array([-1,5,10,99], dtype=float)

print(arr2.dtype)
print(arr2)

arr3 = np.array([-1,3,14,"hello",True])

print(arr3)

print(arr3.dtype)

print("==============")

s=pd.Series([-1,5,10,99], dtype=np.float )

print(s.dtype)
print(s.index)

print(s.values)

print(type(s.values))





[-1  5 10 99]
int32
float64
[-1.  5. 10. 99.]
['-1' '3' '14' 'hello' 'True']
<U11
float64
RangeIndex(start=0, stop=4, step=1)
[-1.  5. 10. 99.]
<class 'numpy.ndarray'>


In [40]:
import pandas as pd

s=pd.Series([1,-5,10,9],index=["c","b","a","k"])
display(s)

print("s[0]의 값은:{}".format(s[0]))

print("s[a]의 값은:{}".format(s["a"]))

print("="*30)
print("s[0:3]의 값은:{}".format(s[0:3]))

print(s["c":"a"])

result=0.0





c     1
b    -5
a    10
k     9
dtype: int64

s[0]의 값은:1
s[a]의 값은:10
s[0:3]의 값은:c     1
b    -5
a    10
dtype: int64
c     1
b    -5
a    10
dtype: int64


In [119]:
#a공장의 2019-01-01부터 10일간 생산량을 series로 저장
#생산량은 평균 50이고 표준편차가 5인 정규분포에서
#random 하에 추출 (생산량은 정수로 처리)
#ex 2019-01-01 54
# 2019-01-02 49
from dateutil.parser import parse
import pandas as pd

print(parse("2019-01-01"))
mean=50
std=5

my_list = []


print(my_list)
arr = np.random.normal(mean,std,(1000,))
print(arr[8])
print(arr[0].dtype)
for i in range(0, 10):

    
    my_list.append(i)
    s=pd.Series([arr[i]],index=[now])
print(my_list)
print(s)



2019-01-01 00:00:00
[]
51.95500279768811
float64
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
2019-01-01    49.837817
dtype: float64


In [120]:
from dateutil.parser import parse
import pandas as pd

print(parse("2019-01-01"))
mean=70
std=8


arr = np.random.normal(mean,std,(1000,))
print(arr[0])
print(arr[0].dtype)
for i in range(0, 8):
    for arr in i:
        print(arr)
    arr1=int(arr[i])
    s=pd.Series([arr1],index=[now])
    print(s)

2019-01-01 00:00:00
63.380538705042035
float64


TypeError: 'int' object is not iterable

In [160]:
#풀이
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

mean=70
std=8
i=10
start_day = datetime(2019,1,1)

    
s_value=[int(x) for x in np.random.normal(50,5,(10,))]
print(s_value)

s_date=[start_day+timedelta(days=x) for x in range 10]

s=pd.Series(s_value,index=s_date)

print(s)

SyntaxError: invalid syntax (<ipython-input-160-b1f222d79133>, line 15)

In [164]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

s_date=[start_day+timedelta(days=x) for x in range (0,10)]

print(s_date)

[datetime.datetime(2019, 1, 1, 0, 0), datetime.datetime(2019, 1, 2, 0, 0), datetime.datetime(2019, 1, 3, 0, 0), datetime.datetime(2019, 1, 4, 0, 0), datetime.datetime(2019, 1, 5, 0, 0), datetime.datetime(2019, 1, 6, 0, 0), datetime.datetime(2019, 1, 7, 0, 0), datetime.datetime(2019, 1, 8, 0, 0), datetime.datetime(2019, 1, 9, 0, 0), datetime.datetime(2019, 1, 10, 0, 0)]


In [171]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

mean=70
std=8
i=10
start_day = datetime(2019,1,1)

    
s_value=[int(x) for x in np.random.normal(50,5,(10,))]
s_date=[start_day+timedelta(days=x) for x in range (0,10)]


print(s_value)
print(s_date)
print("================")

s=pd.Series(s_value,index=s_date)


list=[1,2,3]
s1=pd.Series(list)
print(s1)
print(s)

[46, 49, 53, 49, 45, 44, 55, 54, 49, 47]
[datetime.datetime(2019, 1, 1, 0, 0), datetime.datetime(2019, 1, 2, 0, 0), datetime.datetime(2019, 1, 3, 0, 0), datetime.datetime(2019, 1, 4, 0, 0), datetime.datetime(2019, 1, 5, 0, 0), datetime.datetime(2019, 1, 6, 0, 0), datetime.datetime(2019, 1, 7, 0, 0), datetime.datetime(2019, 1, 8, 0, 0), datetime.datetime(2019, 1, 9, 0, 0), datetime.datetime(2019, 1, 10, 0, 0)]
0    1
1    2
2    3
dtype: int64
2019-01-01    46
2019-01-02    49
2019-01-03    53
2019-01-04    49
2019-01-05    45
2019-01-06    44
2019-01-07    55
2019-01-08    54
2019-01-09    49
2019-01-10    47
dtype: int64


In [158]:

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

start_day = datetime(2019,1,1)

    

print(s_value)

s=pd.Series([int(x) for x in np.random.normal(50,5,(10,))]
            ,index=[start_day+timedelta(days=x) for x in range i])

print(s)








SyntaxError: invalid syntax (<ipython-input-158-80447b63a468>, line 13)

In [143]:
import numpy as np
import pandas as pd


#시리즈는 여러가지 기능이 확장된 느낌


my_dict={"서울":3000,"인천" : 5000 , "제주" : 3000 }

print(my_dict)

s=pd.Series(my_dict)

#시리즈 이름
s.name="지역별 가격 데이터"


#인덱스 이름
s.index.name="지역"

#인덱스 수정
idx=["seoul","inchon","jeju"]
s.index=idx
s


{'서울': 3000, '인천': 5000, '제주': 3000}


seoul     3000
inchon    5000
jeju      3000
Name: 지역별 가격 데이터, dtype: int64

In [ ]:
#pandas:
# 2개의 자료구조 
#1.Series 넘파이의1차 어레이(1차배열)
#numpy 1차원 array 와 유사한데 다른점은 넘파이는 따로 인덱스 구문을 이용해서 쓰는데
#시리즈는 인덱스값을 들고있다 기본적인 index(0~)을 사용할 수 있다.

#2.Dataframe  2차 어레이 -> 여러개의 시리즈(1차원)를 모아둔게 데이터 프레임(2차원)
# 즉 여러개의 시리즈를 모아놓은 테이블형식
# 딕셔너리를 예로들어 사용하기시작 (딴걸써도되지만 편하기때문에) 가장많이 쓰는건 딕셔너리 리스트 넘파이











In [13]:
# -dictionary 를 이용한 dataframe 생성

import numpy as np
import pandas as pd   #위쪽과 공유하기때문에 매번쓸필요없다 


                          # my_dict ={"key":"value"}  # 중괄호로 표현 key와 value 쌍이 딕셔너리  , 키만나오면  set
                          # my_dict ={1,2,3,4} #set

#my_dict = dict() #empty dicttionary 생성 
#my_dict = {}
#학생정보 dictionary {이름, 학과, 학번, 평점}


mydict = {"이름":["이지인","박동훈","홍길동"],
          "학과":["컴퓨터","수학과","철학"],
          "학년":[1,2,3,],
          "평점":[4.0,3.5,3.0]}

print(mydict["학과"][1])

df= pd.DataFrame(mydict)
df

#데이터프레임 ->3가지  코드로부터,네트워크,파일,데이터베이스 등으로 읽어옴
#그래서 가장쉬운 csv파일

#database 로 부터 data를 읽어서 dataframe으로 생성
#mysql database 를 이용




수학과


이름   학과  학년   평점
0  이지인  컴퓨터   1  4.0
1  박동훈  수학과   2  3.5
2  홍길동   철학   3  3.0

In [35]:
#py mysql module 을 이용

import pymysql.cursors    #conda install pymysql 설치해야함 아나콘다 콘솔창에 
import numpy as np
import pandas as pd



# mysql 포트번호 를 알아야함 아이디와 패스워드 -> 여러 데이터베이스중 어떤 데이터베이스에 접근할지 지정

conn=pymysql.connect(host ="localhost",#mysql이 설치된 컴퓨터 ip 
                user="python",    # 사용자 계정 ID
                password="python", # 사용자 password
                db="library",     # 사용할 database 
                charset="UTF8"
                ) # 출력화면   <pymysql.connections.Connection at 0x6942dd8>

#sql을 작성 
#제공한 script 파일에 books 라는 table이 있다 


keyword =input("키워드 입력하세요")
sql = "SELECT bisbn,btitle,bauthor,bprice FROM books WHERE btitle LIKE '%{}%'".format(keyword)



df=pd.read_sql(sql, con=conn) #pandas 가 sql을 실행시켜서 그결과를 dataframe으로 생성해주는 함수
#df.to_json("./data/sample/books.json")

display(df)
conn.close()#종료처리









키워드 입력하세요int


bisbn                                             btitle  \
0  978-89-7914-672-1  IT CookBook, 아날로그 CMOS 집적회로 설계 : Design of Ana...   
1  978-89-7914-815-2  IT CookBook, 현대 전력전자공학: Introduction to Modern...   
2  978-89-98756-39-0  IT CookBook, 현대 반도체 소자 공학 : Modern Semiconduct...   
3  978-89-98756-57-4                                MOS PowerPoint 2007   
4  979-11-5664-113-1          Introduction To Algorithms, Third Edition   

                               bauthor  bprice  
0               버자드 라자비(Behzad Razavi)   32000  
1                          안제이 트지나로브스키   25000  
2             첸밍 후(Chenming Calvin Hu)   25000  
3                             이지윤, 김선희   13000  
4  토머스 코멘, 찰스 레이서손, 로날드 리베스트, 클리포드 스타인   47000

In [47]:
#구글 확장 프로그램설치 json 포멧을 바꿔주는


#"bisbn": {}, json 파일을 읽어보니 키와 벨류 형태
#즉 json이라는 데이터표현형태는 python의 dictionary와 같은형태를 가짐
import numpy as np

import pandas as pd

import json



#일단 python의 파일 처리 기능을 이용해서 file을 열고 데이터를 읽어들일것


file = open("./data/sample/books.json")

dict = json.load(file)

file.close()

for tmp in dict["btitle"].values():
    print(tmp)

df=pd.DataFrame(dict)
display(df)











Head First Java: 뇌 회로를 자극하는 자바 학습법(개정판)
뇌를 자극하는 Java 프로그래밍
모던 웹을 위한 JavaScript + jQuery 입문(개정판) : 자바스크립트에서 제이쿼리, 제이쿼리 모바일까지 한 권으로 끝낸다
JavaScript+jQuery 정복 : 보고, 이해하고, 바로 쓰는 자바스크립트 공략집
이것이 자바다 : 신용권의 Java 프로그래밍 정복
Head First JavaScript Programming : 게임과 퍼즐로 배우는 자바스크립트 입문서
Head First JavaScript : 대화형 웹 애플리케이션의 시작
UML과 JAVA로 배우는 객체지향 CBD 실전 프로젝트 : 도서 관리 시스템
IT CookBook, 웹 프로그래밍 입문 : XHTML, CSS2, JavaScript
자바스크립트 성능 최적화: High Performance JavaScript
IT CookBook, Java for Beginner
IT CookBook, 인터넷 프로그래밍 입문: HTML, CSS, JavaScript


bisbn                                             btitle  \
0       89-7914-371-0            Head First Java: 뇌 회로를 자극하는 자바 학습법(개정판)   
1       89-7914-397-4                                 뇌를 자극하는 Java 프로그래밍   
10  978-89-98756-79-6                     IT CookBook, Java for Beginner   
11  978-89-98756-89-5   IT CookBook, 인터넷 프로그래밍 입문: HTML, CSS, JavaScript   
2   978-89-6848-042-3  모던 웹을 위한 JavaScript + jQuery 입문(개정판) : 자바스크립트에...   
3   978-89-6848-132-1  JavaScript+jQuery 정복 : 보고, 이해하고, 바로 쓰는 자바스크립트 공략집   
4   978-89-6848-147-5                       이것이 자바다 : 신용권의 Java 프로그래밍 정복   
5   978-89-6848-156-7  Head First JavaScript Programming : 게임과 퍼즐로 배우...   
6   978-89-7914-582-3           Head First JavaScript : 대화형 웹 애플리케이션의 시작   
7   978-89-7914-659-2        UML과 JAVA로 배우는 객체지향 CBD 실전 프로젝트 : 도서 관리 시스템   
8   978-89-7914-832-9  IT CookBook, 웹 프로그래밍 입문 : XHTML, CSS2, JavaScript   
9   978-89-7914-855-8         자바스크립트 성능 최적화: High Performance JavaScript   

                           bauthor  bprice  
0                   케이시 시에라,버트 베이츠   28000  
1                              김윤명   27000  
10                        황희정, 강운구   23000  
11  주성례(저자), 정선호(저자), 한민형(저자), 권원상   22000  
2                              윤인성   32000  
3                              김상형   28000  
4                              신용권   30000  
5                 에릭 프리먼, 엘리자베스 롭슨   36000  
6                          마이클 모리슨   28000  
7                              채흥석   40000  
8                         김형철, 안치현   23000  
9                         니콜라스 자카스   20000

In [ ]:
# open api 를 이용해서 json data 를 받은다음

#해당 data를 처리해서 dataframe으로 생성

In [ ]:
import numpy as np
import pandas as pd
import urllib # 외부 url 호출
import json   # 


#day=input("날짜를 입력하세요")
day=20190219

movie_url ="http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=430156241533f1d058c603178cc3ca0e&targetDt={}".format(day)
movie_page = urllib.request.urlopen(movie_url)
json_page=json.loads(movie_page.read())

print(json_page)

