In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings






train = pd.read_csv("./data/titanic/train.csv")


train.loc[train["Sex"]=="male","Sex"]=1
train.loc[train["Sex"]=="female","Sex"]=0

train.Age=train.Age.fillna(0)


train.loc[(train.Name.str.contains('Mrs'))&(train["Age"]==0),"Age"]=31

train.loc[(train.Name.str.contains('Mr'))&(train["Age"]==0),"Age"]=26


train.loc[train["Age"]==0,"Age"]=23


n=np.array(train["Age"])

n1=[]
n2=[]
n3=[]

for i in train["Age"]:
    
    if (23>=i) & (i>0):
        n1.append(1)
        n2.append(0)
        n3.append(0)
    elif (31>=i) & (i>23):
        n1.append(0)
        n2.append(1)
        n3.append(0)
    elif (81>=i) & (i>31):
        n1.append(0)
        n2.append(0)
        n3.append(1)
train["Age1"]=n1
train["Age2"]=n2
train["Age3"]=n3
        
train.drop('Age', axis=1, inplace=True)

df1=pd.DataFrame(train["Fare"])

mms = MinMaxScaler().fit_transform(df1.values)



train["Fare"]=mms




train.Fare=train.Fare.fillna(0.06285842768394742)



train.loc[train["Pclass"]==3,"Pclass"]=4
train.loc[train["Pclass"]==1,"Pclass"]=3
train.loc[train["Pclass"]==4,"Pclass"]=1

train.drop("Name",axis=1, inplace=True)
train.drop("Ticket",axis=1, inplace=True)
train.drop("Cabin",axis=1, inplace=True)
train.drop("Embarked",axis=1, inplace=True)
train


dff=pd.DataFrame(train)
#and 연산 


dff.drop("PassengerId",axis=1, inplace=True)
y_data=dff["Survived"].values.reshape(-1,1)
x_data=dff.drop("Survived",axis=1, inplace=False).values


X = tf.placeholder(shape=[None,8],dtype = tf.float32  ) #행 숫자는 무상관
Y = tf.placeholder(shape=[None,1],dtype = tf.float32  )


keep = tf.placeholder(dtype = tf.float32)


W1 = tf.Variable(tf.random_normal([8,5]), name ="weight1")  #일반 로지스틱
b1 = tf.Variable(tf.random_normal([5]), name ="bias1")
layer1 = tf.nn.relu(tf.matmul(X,W1)+b1)

W2 = tf.Variable(tf.random_normal([5,10]), name ="weight2")
b2 = tf.Variable(tf.random_normal([10]), name ="bias2")
layer2 = tf.nn.relu(tf.matmul(layer1,W2)+b2)

W3 = tf.Variable(tf.random_normal([10,2]), name ="weight3")
b3 = tf.Variable(tf.random_normal([2]), name ="bias3")

H = tf.matmul(layer2,W3) +b3

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = H,labels=Y))

#6. Train
train = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(cost)

#7. Session & 초기화
sess=tf.Session()
sess.run(tf.global_variables_initializer())




for step in range(30000):
    _,cost_val = sess.run([train,cost], feed_dict={X:x_data,Y:y_data} )
    if step%3000 == 0 :
        print("cost:{}".format(cost_val))


print(H)
predict=tf.argmax(H,1)
correct=tf.equal(predict, tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(correct, dtype=tf.float32))
print("="*10)

#정확도 출력
print(sess.run(accuracy, feed_dict={X:x_data,Y:y_data }))

test = pd.read_csv("./data/titanic/test.csv")


test.loc[test["Sex"]=="male","Sex"]=1
test.loc[test["Sex"]=="female","Sex"]=0

test.Age=test.Age.fillna(0)


display(test)

test.loc[(test.Name.str.contains('Mrs'))&(test["Age"]==0),"Age"]=31

test.loc[(test.Name.str.contains('Mr'))&(test["Age"]==0),"Age"]=26


test.loc[test["Age"]==0,"Age"]=23


m=np.array(test["Age"])

m1=[]
m2=[]
m3=[]

for i in test["Age"]:
    
    if (23>=i) & (i>0):
        m1.append(1)
        m2.append(0)
        m3.append(0)
    elif (31>=i) & (i>23):
        m1.append(0)
        m2.append(1)
        m3.append(0)
    elif (81>=i) & (i>31):
        m1.append(0)
        m2.append(0)
        m3.append(1)
test["Age1"]=m1
test["Age2"]=m2
test["Age3"]=m3
        
test.drop('Age', axis=1, inplace=True)

ddf1=pd.DataFrame(test["Fare"])

mmms = MinMaxScaler().fit_transform(ddf1.values)



test["Fare"]=mmms




test.Fare=test.Fare.fillna(0.06285842768394742)



test.loc[test["Pclass"]==3,"Pclass"]=4
test.loc[test["Pclass"]==1,"Pclass"]=3
test.loc[test["Pclass"]==4,"Pclass"]=1

test.drop("Name",axis=1, inplace=True)
test.drop("Ticket",axis=1, inplace=True)
test.drop("Cabin",axis=1, inplace=True)
test.drop("Embarked",axis=1, inplace=True)
test

ddff=pd.DataFrame(test)
#and 연산 

ddff.drop("PassengerId",axis=1, inplace=True)

xx_data=ddff.values


dddff=pd.DataFrame({"Survived","Passenger"})

# for step1 in range(len(xx_data+1)):
#print(xx_data)
predict1=tf.argmax(H,1)

print("============")
display(x_data)
print("============")
display(xx_data)


# for step1 in range(len(xx_data+1)):
#     y_value = sess.run(predict1, feed_dict={X:xx_data})

    


# print(y_value)






cost:2.199160099029541
cost:0.5342050194740295
cost:0.5344207286834717
cost:0.5357809662818909
cost:0.5380313396453857
cost:0.5416554808616638
cost:0.5454498529434204
cost:0.5493849515914917
cost:0.6611558198928833
cost:0.5337923169136047
Tensor("add_2:0", shape=(?, 2), dtype=float32)
0.0


PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

array([[1., 1., 1., ..., 1., 0., 0.],
       [3., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 0., 0.],
       [3., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 1.]])

array([[1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 0.]])

In [9]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler



test = pd.read_csv("./data/titanic/test.csv")


test.loc[test["Sex"]=="male","Sex"]=1
test.loc[test["Sex"]=="female","Sex"]=0

test.Age=test.Age.fillna(0)


display(test)

test.loc[(test.Name.str.contains('Mrs'))&(test["Age"]==0),"Age"]=31

test.loc[(test.Name.str.contains('Mr'))&(test["Age"]==0),"Age"]=26


test.loc[test["Age"]==0,"Age"]=23


m=np.array(test["Age"])

m1=[]
m2=[]
m3=[]

for i in test["Age"]:
    
    if (23>=i) & (i>0):
        m1.append(1)
        m2.append(0)
        m3.append(0)
    elif (31>=i) & (i>23):
        m1.append(0)
        m2.append(1)
        m3.append(0)
    elif (81>=i) & (i>31):
        m1.append(0)
        m2.append(0)
        m3.append(1)
test["Age1"]=m1
test["Age2"]=m2
test["Age3"]=m3
        
test.drop('Age', axis=1, inplace=True)

ddf1=pd.DataFrame(test["Fare"])

mmms = MinMaxScaler().fit_transform(ddf1.values)



test["Fare"]=mmms




test.Fare=test.Fare.fillna(0.06285842768394742)



test.loc[test["Pclass"]==3,"Pclass"]=4
test.loc[test["Pclass"]==1,"Pclass"]=3
test.loc[test["Pclass"]==4,"Pclass"]=1

test.drop("Name",axis=1, inplace=True)
test.drop("Ticket",axis=1, inplace=True)
test.drop("Cabin",axis=1, inplace=True)
test.drop("Embarked",axis=1, inplace=True)
test

ddff=pd.DataFrame(test)
#and 연산 

ddff.drop("PassengerId",axis=1, inplace=True)

xx_data=ddff.values


dddff=pd.DataFrame({"Survived","Passenger"})

# for step1 in range(len(xx_data+1)):
#print(xx_data)
predict1=tf.argmax(H,1)

print("1============")
display(x_data)
print("2============")
display(xx_data)

print(xx_data[0])
y_value=pd.DataFrame()




print(xx_data.shape)
display(xx_data)


y_value = sess.run(predict1, feed_dict={X:[xx_data]})

#print(y_value)



#for n in range(0,418):
#    y_value = sess.run(predict1, feed_dict={X:xx_data[n]})

#print(y_value)
#for step1 in range(len(xx_data+1)):
#    y_value = sess.run(predict1, feed_dict={X:xx_data})

    
    
#y_value = sess.run(y_data, feed_dict={X:xx_data})
print("3============")
#y=W3*X+b3
#dddff["Survived"]= y_value
#print( dddff)


PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

1============


array([[1., 1., 1., ..., 1., 0., 0.],
       [3., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 0., 0.],
       [3., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 1.]])

2============


array([[1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 0.]])

[1.         1.         0.         0.         0.01528158 0.
 0.         1.        ]
(418, 8)


array([[1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 0.]])

ValueError: Cannot feed value of shape (1, 418, 8) for Tensor 'Placeholder:0', which has shape '(?, 8)'

In [5]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings





train = pd.read_csv("./data/titanic/train.csv")


train.loc[train["Sex"]=="male","Sex"]=1
train.loc[train["Sex"]=="female","Sex"]=0

train.Age=train.Age.fillna(0)


train.loc[(train.Name.str.contains('Mrs'))&(train["Age"]==0),"Age"]=31

train.loc[(train.Name.str.contains('Mr'))&(train["Age"]==0),"Age"]=26


train.loc[train["Age"]==0,"Age"]=23


n=np.array(train["Age"])

n1=[]
n2=[]
n3=[]

for i in train["Age"]:
    
    if (23>=i) & (i>0):
        n1.append(1)
        n2.append(0)
        n3.append(0)
    elif (31>=i) & (i>23):
        n1.append(0)
        n2.append(1)
        n3.append(0)
    elif (81>=i) & (i>31):
        n1.append(0)
        n2.append(0)
        n3.append(1)
train["Age1"]=n1
train["Age2"]=n2
train["Age3"]=n3
        
train.drop('Age', axis=1, inplace=True)

df1=pd.DataFrame(train["Fare"])

mms = MinMaxScaler().fit_transform(df1.values)



train["Fare"]=mms




train.Fare=train.Fare.fillna(0.06285842768394742)



train.loc[train["Pclass"]==3,"Pclass"]=4
train.loc[train["Pclass"]==1,"Pclass"]=3
train.loc[train["Pclass"]==4,"Pclass"]=1

train.drop("Name",axis=1, inplace=True)
train.drop("Ticket",axis=1, inplace=True)
train.drop("Cabin",axis=1, inplace=True)
train.drop("Embarked",axis=1, inplace=True)
train


dff=pd.DataFrame(train)
#and 연산 




dff.drop("PassengerId",axis=1, inplace=True)
y_data=dff["Survived"].values.reshape(-1,1)
x_data=dff.drop("Survived",axis=1, inplace=False).values

print(len(x_data)*2/3)

print(len(x_data)/3)

number=int(len(x_data)*2/3)
x1_data=x_data[0:number]
x2_data=x_data[number:-1]

y1_data=y_data[0:number]
y2_data=y_data[number:-1]



X = tf.placeholder(shape=[None,8],dtype = tf.float32  ) #행 숫자는 무상관
Y = tf.placeholder(shape=[None,1],dtype = tf.float32  )


keep = tf.placeholder(dtype = tf.float32)



w=tf.Variable(tf.random_normal([8,1]),name="weight" )  
b=tf.Variable(tf.random_normal([1]) , name="bias")
print("w:{}".format(w.get_shape()))
# h=tf.matmul(x,w)+b #멀티플에 하이파시스 여서 배열곱 x,w해줌
logit=tf.matmul(X,w)+b

h=tf.sigmoid(logit) # 𝐻𝑥=11+𝑒−(𝑋𝑊+𝑏) 이 수식을 해줌



cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,labels=Y ))



train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

#print(cost)


#세션 초기화 -> 런을 만들고 초기화
sess=tf.Session()
sess.run(tf.global_variables_initializer())

#학습

for step in range(3500):
    _,cost_val = sess.run([train,cost], feed_dict={X:x_data , Y:y_data})
    
    if step%350==0 :
        print("cost:{}".format(cost_val))

        


        
#accuracy 예측값을 알아내는것 
predict = tf.cast(h>0.5 ,dtype=tf.float32) #원래는 정수를 실수로 , 실수를 정수로 바꿔주는 cast 타입변환 1.0 0.0 으로 변환인듯?
                                            #0.5보다 크면 1로 떨어짐
correct = tf.equal(predict,Y) #실데이터와 예측한 것을 비교하는것 

accuracy = tf.reduce_mean(tf.cast(correct , dtype=tf.float32))


print("정확도 ={}".format(sess.run(accuracy ,feed_dict={X:x2_data,Y:y2_data} ) ))




test = pd.read_csv("./data/titanic/test.csv")


test.loc[test["Sex"]=="male","Sex"]=1
test.loc[test["Sex"]=="female","Sex"]=0

test.Age=test.Age.fillna(0)


display(test)

test.loc[(test.Name.str.contains('Mrs'))&(test["Age"]==0),"Age"]=31

test.loc[(test.Name.str.contains('Mr'))&(test["Age"]==0),"Age"]=26


test.loc[test["Age"]==0,"Age"]=23


m=np.array(test["Age"])

m1=[]
m2=[]
m3=[]

for i in test["Age"]:
    
    if (23>=i) & (i>0):
        m1.append(1)
        m2.append(0)
        m3.append(0)
    elif (31>=i) & (i>23):
        m1.append(0)
        m2.append(1)
        m3.append(0)
    elif (81>=i) & (i>31):
        m1.append(0)
        m2.append(0)
        m3.append(1)
test["Age1"]=m1
test["Age2"]=m2
test["Age3"]=m3
        
test.drop('Age', axis=1, inplace=True)

ddf1=pd.DataFrame(test["Fare"])

mmms = MinMaxScaler().fit_transform(ddf1.values)



test["Fare"]=mmms




test.Fare=test.Fare.fillna(0.06285842768394742)



test.loc[test["Pclass"]==3,"Pclass"]=4
test.loc[test["Pclass"]==1,"Pclass"]=3
test.loc[test["Pclass"]==4,"Pclass"]=1

test.drop("Name",axis=1, inplace=True)
test.drop("Ticket",axis=1, inplace=True)
test.drop("Cabin",axis=1, inplace=True)
test.drop("Embarked",axis=1, inplace=True)
test

ddff=pd.DataFrame(test)
#and 연산 

ddff.drop("PassengerId",axis=1, inplace=True)

xx_data=ddff.values


dddff=pd.DataFrame(columns=["PassengerId","Survived"])

# for step1 in range(len(xx_data+1)):
#print(xx_data)


print("1============")
display(x_data)
print("2============")
display(xx_data)

print(xx_data[0])
y_value=pd.DataFrame()




print(xx_data.shape)
display(xx_data)


y_value = sess.run(predict, feed_dict={X:xx_data})

print(y_value)


#dddff[Survived]=y_value

print(dddff)





test = pd.read_csv("./data/titanic/test.csv")
ddff2=pd.DataFrame(test["PassengerId"])


print(y_value.shape)
print(y_value)

y_value=y_value.reshape(-1)
#y_value = map(int, y_value)
y_value= [int (i) for i in y_value]
print("========")
print(ddff2)

dddff["PassengerId"] =ddff2.values
dddff["Survived"]=y_value
display(dddff)

dddff.to_csv("./data/submittaitanic", index=False)


594.0
297.0
w:(8, 1)
cost:1.5723612308502197
cost:0.9757540225982666
cost:0.7419275641441345
cost:0.621100127696991
cost:0.5584478378295898
cost:0.523802638053894
cost:0.5031883716583252
cost:0.4901001453399658
cost:0.48133426904678345
cost:0.47520551085472107
정확도 =0.7972972989082336


PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

1============


array([[1., 1., 1., ..., 1., 0., 0.],
       [3., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 1., ..., 1., 0., 0.],
       [3., 1., 0., ..., 0., 1., 0.],
       [1., 1., 0., ..., 0., 0., 1.]])

2============


array([[1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 0.]])

[1.         1.         0.         0.         0.01528158 0.
 0.         1.        ]
(418, 8)


array([[1., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [2., 1., 0., ..., 0., 0., 1.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 0.]])

[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.

TypeError: Index(...) must be called with a collection of some kind, False was passed