In [45]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")

display(train)

print("=====")
display(test)

print(int(len(train)))

train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]

print(train1[0:100])

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
5          0       0       0       0       0       0       0       0       0   
6          7       0       0       0       0       0       0       0       0   
7          3       0       0       0       0       0       0       0       0   
8          5       0       0       0       0       0       0       0       0   
9          3       0       0       0       0       0       0       0       0   
10         8       0       0       0       0       0       0       0       0   
11         9       0       0       0       0       0       0       0       0   
12         1       0       0       0       0       0       0       0       0   
13         3       0       0       0       0       0       0       0       0   
14         3       0       0       0       0       0       0       0       0   
15         1       0       0       0       0       0       0       0       0   
16         2       0       0       0       0       0       0       0       0   
17         0       0       0       0       0       0       0       0       0   
18         7       0       0       0       0       0       0       0       0   
19         5       0       0       0       0       0       0       0       0   
20         8       0       0       0       0       0       0       0       0   
21         6       0       0       0       0       0       0       0       0   
22         2       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
24         2       0       0       0       0       0       0       0       0   
25         3       0       0       0       0       0       0       0       0   
26         6       0       0       0       0       0       0       0       0   
27         9       0       0       0       0       0       0       0       0   
28         9       0       0       0       0       0       0       0       0   
29         7       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970      2       0       0       0       0       0       0       0       0   
41971      3       0       0       0       0       0       0       0       0   
41972      4       0       0       0       0       0       0       0       0   
41973      4       0       0       0       0       0       0       0       0   
41974      3       0       0       0       0       0       0       0       0   
41975      9       0       0       0       0       0       0       0       0   
41976      2       0       0       0       0       0       0       0       0   
41977      4       0       0       0       0       0       0       0       0   
41978      4       0       0       0       0       0       0       0       0   
41979      4       0       0       0       0       0       0       0       0   
41980      7       0       0       0       0       0       0       0       0   
41981      2       0       0       0       0       0       0       0       0   
41982      8       0       0       0       0       0       0       0       0   
41983      7       0       0       0       0       0       0       0       0   
41984      3       0       0       0       0       0       0       0       0   
41985      3       0       0       0       0       0       0       0       0   
41986      0       0       0       0       0       0       0       0       0   
41987      5       0       0       0       0       0       0       0       0   
41988  

=====


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       0       0       0       0       0       0       0   
12          0       0       0       0       0       0       0       0       0   
13          0       0       0       0       0       0       0       0       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       0       0       0       0       0       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       0       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       0       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       0       0   
23          0       0       0       0       0       0       0       0       0   
24          0       0       0       0       0       0       0       0       0   
25          0       0       0       0       0       0       0       0       0   
26          0       0       0       0       0       0       0       0       0   
27          0       0       0       0       0       0       0       0       0   
28          0       0       0       0       0       0       0       0       0   
29          0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27970       0       0       0       0       0       0       0       0       0   
27971       0       0       0       0       0       0       0       0       0   
27972       0       0       0       0       0       0       0       0       0   
27973       0       0       0       0       0       0       0       0       0   
27974       0       0       0       0       0       0       0       0       0   
27975       0       0       0       0       0       0       0       0       0   
27976       0       0       0       0       0       0       0       0       0   
27977       0       0       0       0       0       0       0       0       0   
27978       0       0       0       0       0       0       0       0       0   
27979       0       0       0       0       0       0       0       0       0   
27980       0       0       0       0       0       0       0       0       0   
27981       0       0       0       0       0       0       0       0       0   
27982       0       0       0       0       0       0       0       0       0   
27983       0       0       0       0       0       0       0       0       0   
27984       0       0       0       0       0       0       0       0       0   
27985       0       0       0       0       0       0       0       0       0   
27986       0       0       0       0       0       0       0       0       0   
27987       0       0       0       0 

42000
    pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0        0       0       0       0       0       0       0       0       0   
1        0       0       0       0       0       0       0       0       0   
2        0       0       0       0       0       0       0       0       0   
3        0       0       0       0       0       0       0       0       0   
4        0       0       0       0       0       0       0       0       0   
5        0       0       0       0       0       0       0       0       0   
6        0       0       0       0       0       0       0       0       0   
7        0       0       0       0       0       0       0       0       0   
8        0       0       0       0       0       0       0       0       0   
9        0       0       0       0       0       0       0       0       0   
10       0       0       0       0       0       0       0       0       0   
11       0       0       0       0       0       0       0

In [57]:
#print(train["pixel1"]==1,)
#df.loc[df["이름"] =="박동훈","이름":"학점"]

#print(train.shape)


#display(train1)
#display(train2)
#print(train.index.values)
nn=int(len(train1))
print(nn)

tf.reset_default_graph()

X=tf.placeholder(shape=[None,784], dtype=tf.float32)
Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지

#3 convolution layer
#3.1 convolution layer
# 입력 데이터의 형태를 convolution 할수 있도록 4차배열로 reshape 그럼 입력데이터의 형태를 보는방법이 뭐였지?
# 들어오는 데이터 X의 shape = None,784
X_img = tf.reshape(X, shape=[-1,28,28,1])

print(X_img)

W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))
#3.2 convolution layer

L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")
#RELU

L1 = tf.nn.relu(L1)

print(L1)
p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")
print(p1)



#layer two 다른형태 위에꺼 복사해도됨
# W2=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))
# L1 = tf.nn.conv2d(p1,W1,strides=[1,1,1,1], padding="SAME") 이런식으로


#filter,convolution,relu

L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)



print("L2")
print(L2.shape)

L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

print(L2.shape)

#########CONVOLUTION LAYER 끝

#4. NURAL NETWORK

print("L2[0]")

print(L2)

L2=tf.reshape(L2,shape=[-1,7*7*64])

#print(L2.shape)

# 5. weight & bias

W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
b2=tf.Variable(tf.random_normal([256]),name="bias2" )

_layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
b3=tf.Variable(tf.random_normal([256]),name="bias3" )

_layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
b4=tf.Variable(tf.random_normal([10]),name="bias4" )

# hypothesis 가설만들어야함


H = tf.matmul(layer2,W4)+b4

#cost 함수

cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

train = tf.train.AdamOptimizer(learning_rate=0.001).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

#학습

num_of_epoch = 10
batch_size=100

print(train1[0:100])
#num_of_iter = int(nn)
#print(type(num_of_iter))

n=0
n1=100
for step in range(num_of_epoch):
    num_of_iter = int(nn)
    
    for i in range(int(num_of_iter/batch_size)):
        
        
        batch_x = train1[n:n1]
        batch_y = train2[n:n1]
        
        print(batch_y.shape)
        _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.5})

        n=n+n1
        n1=n1+n1
        
        
        
    print("cost : {}".format(cost_val))
    
    
    

predict = tf.argmax(H,1)
correct=tf.equal(predict , tf.argmax(Y,1)) 

accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

result_sum=0
num_of_iter = int(nn)
n=0
for i in range(num_of_iter):
    batch_x=train1[n]
    batch_y =train2[n]
    correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
    result_sum += correct_num
    n=n+1
    
#tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
#print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

print("정확도:{}".format(result_sum/10000))








42000
Tensor("Reshape:0", shape=(?, 28, 28, 1), dtype=float32)
Tensor("Relu:0", shape=(?, 28, 28, 32), dtype=float32)
Tensor("MaxPool:0", shape=(?, 14, 14, 32), dtype=float32)
L2
(?, 14, 14, 64)
(?, 7, 7, 64)
L2[0]
Tensor("max_pooling2d/MaxPool:0", shape=(?, 7, 7, 64), dtype=float32)
    pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0        0       0       0       0       0       0       0       0       0   
1        0       0       0       0       0       0       0       0       0   
2        0       0       0       0       0       0       0       0       0   
3        0       0       0       0       0       0       0       0       0   
4        0       0       0       0       0       0       0       0       0   
5        0       0       0       0       0       0       0       0       0   
6        0       0       0       0       0       0       0       0       0   
7        0       0       0       0       0       0       0       0       0   
8        0   

AttributeError: 'Series' object has no attribute 'reshape'

In [91]:













tf.reset_default_graph() 

df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)
print(arr)

df1=arr


df2=pd.DataFrame()

#def
#df1=

for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

print(df1)
display(df2)
tr2=int(len(train2))

print(df1[train2[0]])
for n in range(0,tr2):
    df2[n]=df1[train2[n]]

display(df2)
#print(df1[train2[1]])

df4=pd.DataFrame()

df4=df2.transpose()

display(df4)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0  0
1  1  1  1  1  1  1  1  1  1  1
2  2  2  2  2  2  2  2  2  2  2
3  3  3  3  3  3  3  3  3  3  3
4  4  4  4  4  4  4  4  4  4  4
5  5  5  5  5  5  5  5  5  5  5
6  6  6  6  6  6  6  6  6  6  6
7  7  7  7  7  7  7  7  7  7  7
8  8  8  8  8  8  8  8  8  8  8
9  9  9  9  9  9  9  9  9  9  9

[0 1 0 0 0 0 0 0 0 0]


0      1      2      3      4      5      6      7      8      9      ...  \
0      0      1      0      0      1      1      0      0      0      0  ...   
1      1      0      1      0      0      0      0      0      0      0  ...   
2      0      0      0      0      0      0      0      0      0      0  ...   
3      0      0      0      0      0      0      0      1      0      1  ...   
4      0      0      0      1      0      0      0      0      0      0  ...   
5      0      0      0      0      0      0      0      0      1      0  ...   
6      0      0      0      0      0      0      0      0      0      0  ...   
7      0      0      0      0      0      0      1      0      0      0  ...   
8      0      0      0      0      0      0      0      0      0      0  ...   
9      0      0      0      0      0      0      0      0      0      0  ...   

   41990  41991  41992  41993  41994  41995  41996  41997  41998  41999  
0      0      0      0      0      0      1      0      0      0      0  
1      0      1      0      0      0      0      1      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      1      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      1      0      0      0      0      0  
5      0      0      0      0      0      0      0      0      0      0  
6      0      0      0      1      0      0      0      0      1      0  
7      0      0      0      0      0      0      0      1      0      0  
8      0      0      0      0      0      0      0      0      0      0  
9      0      0      1      0      0      0      0      0      0      1  

[10 rows x 42000 columns]

In [101]:
df4=pd.DataFrame()

df4=df2.transpose()

display(df4)

0      1      2      3      4      5      6      7      8      9      ...  \
0      0      1      0      0      1      1      0      0      0      0  ...   
1      1      0      1      0      0      0      0      0      0      0  ...   
2      0      0      0      0      0      0      0      0      0      0  ...   
3      0      0      0      0      0      0      0      1      0      1  ...   
4      0      0      0      1      0      0      0      0      0      0  ...   
5      0      0      0      0      0      0      0      0      1      0  ...   
6      0      0      0      0      0      0      0      0      0      0  ...   
7      0      0      0      0      0      0      1      0      0      0  ...   
8      0      0      0      0      0      0      0      0      0      0  ...   
9      0      0      0      0      0      0      0      0      0      0  ...   

   41990  41991  41992  41993  41994  41995  41996  41997  41998  41999  
0      0      0      0      0      0      1      0      0      0      0  
1      0      1      0      0      0      0      1      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      1      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      1      0      0      0      0      0  
5      0      0      0      0      0      0      0      0      0      0  
6      0      0      0      1      0      0      0      0      1      0  
7      0      0      0      0      0      0      0      1      0      0  
8      0      0      0      0      0      0      0      0      0      0  
9      0      0      1      0      0      0      0      0      0      1  

[10 rows x 42000 columns]

0  1  2  3  4  5  6  7  8  9
0      0  1  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  1  0  0  0  0  0  0  0  0
3      0  0  0  0  1  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0
5      1  0  0  0  0  0  0  0  0  0
6      0  0  0  0  0  0  0  1  0  0
7      0  0  0  1  0  0  0  0  0  0
8      0  0  0  0  0  1  0  0  0  0
9      0  0  0  1  0  0  0  0  0  0
10     0  0  0  0  0  0  0  0  1  0
11     0  0  0  0  0  0  0  0  0  1
12     0  1  0  0  0  0  0  0  0  0
13     0  0  0  1  0  0  0  0  0  0
14     0  0  0  1  0  0  0  0  0  0
15     0  1  0  0  0  0  0  0  0  0
16     0  0  1  0  0  0  0  0  0  0
17     1  0  0  0  0  0  0  0  0  0
18     0  0  0  0  0  0  0  1  0  0
19     0  0  0  0  0  1  0  0  0  0
20     0  0  0  0  0  0  0  0  1  0
21     0  0  0  0  0  0  1  0  0  0
22     0  0  1  0  0  0  0  0  0  0
23     1  0  0  0  0  0  0  0  0  0
24     0  0  1  0  0  0  0  0  0  0
25     0  0  0  1  0  0  0  0  0  0
26     0  0  0  0  0  0  1  0  0  0
27     0  0  0  0  0  0  0  0  0  1
28     0  0  0  0  0  0  0  0  0  1
29     0  0  0  0  0  0  0  1  0  0
...   .. .. .. .. .. .. .. .. .. ..
41970  0  0  1  0  0  0  0  0  0  0
41971  0  0  0  1  0  0  0  0  0  0
41972  0  0  0  0  1  0  0  0  0  0
41973  0  0  0  0  1  0  0  0  0  0
41974  0  0  0  1  0  0  0  0  0  0
41975  0  0  0  0  0  0  0  0  0  1
41976  0  0  1  0  0  0  0  0  0  0
41977  0  0  0  0  1  0  0  0  0  0
41978  0  0  0  0  1  0  0  0  0  0
41979  0  0  0  0  1  0  0  0  0  0
41980  0  0  0  0  0  0  0  1  0  0
41981  0  0  1  0  0  0  0  0  0  0
41982  0  0  0  0  0  0  0  0  1  0
41983  0  0  0  0  0  0  0  1  0  0
41984  0  0  0  1  0  0  0  0  0  0
41985  0  0  0  1  0  0  0  0  0  0
41986  1  0  0  0  0  0  0  0  0  0
41987  0  0  0  0  0  1  0  0  0  0
41988  1  0  0  0  0  0  0  0  0  0
41989  0  0  0  0  0  1  0  0  0  0
41990  0  0  0  1  0  0  0  0  0  0
41991  0  1  0  0  0  0  0  0  0  0
41992  0  0  0  0  0  0  0  0  0  1
41993  0  0  0  0  0  0  1  0  0  0
41994  0  0  0  0  1  0  0  0  0  0
41995  1  0  0  0  0  0  0  0  0  0
41996  0  1  0  0  0  0  0  0  0  0
41997  0  0  0  0  0  0  0  1  0  0
41998  0  0  0  0  0  0  1  0  0  0
41999  0  0  0  0  0  0  0  0  0  1

[42000 rows x 10 columns]

In [112]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]



nn=int(len(train1))

X=tf.placeholder(shape=[None,784], dtype=tf.float32)
Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지


df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)

df1=arr

df2=pd.DataFrame()


for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):
    df2[n]=df1[train2[n]]

df4=pd.DataFrame()

df4=df2.transpose()






X_img = tf.reshape(X, shape=[-1,28,28,1])

print(X_img)

W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

L1 = tf.nn.relu(L1)
p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)



L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

#########CONVOLUTION LAYER 끝

#4. NURAL NETWORK

print("L2[0]")

print(L2)

L2=tf.reshape(L2,shape=[-1,7*7*64])

#print(L2.shape)

# 5. weight & bias

W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
b2=tf.Variable(tf.random_normal([256]),name="bias2" )

_layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
b3=tf.Variable(tf.random_normal([256]),name="bias3" )

_layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
b4=tf.Variable(tf.random_normal([10]),name="bias4" )

# hypothesis 가설만들어야함


H = tf.matmul(layer2,W4)+b4

#cost 함수

cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

#학습

num_of_epoch = 10
batch_size=100

display(train1)
display(df4)


n=0
n1=100
for step in range(num_of_epoch):
    num_of_iter = int(nn)
    
    for i in range(int(num_of_iter/batch_size)):
        
        
        batch_x = train1[n:n1]
        batch_y = df4[n:n1]
        
        _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

        n=n+n1
        n1=n1+n1
        
        
        
    print("cost : {}".format(cost_val))
    
    
    

predict = tf.argmax(H,1)
correct=tf.equal(predict , tf.argmax(Y,1)) 

accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

result_sum=0
num_of_iter = int(num_of_iter/batch_size)
n=0
n1=100
for i in range(num_of_iter):
    batch_x=train1[n:n1]
    batch_y =df4[n:n1]
    correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
    result_sum += correct_num
    n=n+n1
    n1=n1+n1
    
#tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
#print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

print("정확도:{}".format(result_sum/10000))







Tensor("Reshape:0", shape=(?, 28, 28, 1), dtype=float32)
L2[0]
Tensor("max_pooling2d/MaxPool:0", shape=(?, 7, 7, 64), dtype=float32)


pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       0       0       0       0       0       0       0   
12          0       0       0       0       0       0       0       0       0   
13          0       0       0       0       0       0       0       0       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       0       0       0       0       0       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       0       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       0       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       0       0   
23          0       0       0       0       0       0       0       0       0   
24          0       0       0       0       0       0       0       0       0   
25          0       0       0       0       0       0       0       0       0   
26          0       0       0       0       0       0       0       0       0   
27          0       0       0       0       0       0       0       0       0   
28          0       0       0       0       0       0       0       0       0   
29          0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970       0       0       0       0       0       0       0       0       0   
41971       0       0       0       0       0       0       0       0       0   
41972       0       0       0       0       0       0       0       0       0   
41973       0       0       0       0       0       0       0       0       0   
41974       0       0       0       0       0       0       0       0       0   
41975       0       0       0       0       0       0       0       0       0   
41976       0       0       0       0       0       0       0       0       0   
41977       0       0       0       0       0       0       0       0       0   
41978       0       0       0       0       0       0       0       0       0   
41979       0       0       0       0       0       0       0       0       0   
41980       0       0       0       0       0       0       0       0       0   
41981       0       0       0       0       0       0       0       0       0   
41982       0       0       0       0       0       0       0       0       0   
41983       0       0       0       0       0       0       0       0       0   
41984       0       0       0       0       0       0       0       0       0   
41985       0       0       0       0       0       0       0       0       0   
41986       0       0       0       0       0       0       0       0       0   
41987       0       0       0       0 

0  1  2  3  4  5  6  7  8  9
0      0  1  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  1  0  0  0  0  0  0  0  0
3      0  0  0  0  1  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0
5      1  0  0  0  0  0  0  0  0  0
6      0  0  0  0  0  0  0  1  0  0
7      0  0  0  1  0  0  0  0  0  0
8      0  0  0  0  0  1  0  0  0  0
9      0  0  0  1  0  0  0  0  0  0
10     0  0  0  0  0  0  0  0  1  0
11     0  0  0  0  0  0  0  0  0  1
12     0  1  0  0  0  0  0  0  0  0
13     0  0  0  1  0  0  0  0  0  0
14     0  0  0  1  0  0  0  0  0  0
15     0  1  0  0  0  0  0  0  0  0
16     0  0  1  0  0  0  0  0  0  0
17     1  0  0  0  0  0  0  0  0  0
18     0  0  0  0  0  0  0  1  0  0
19     0  0  0  0  0  1  0  0  0  0
20     0  0  0  0  0  0  0  0  1  0
21     0  0  0  0  0  0  1  0  0  0
22     0  0  1  0  0  0  0  0  0  0
23     1  0  0  0  0  0  0  0  0  0
24     0  0  1  0  0  0  0  0  0  0
25     0  0  0  1  0  0  0  0  0  0
26     0  0  0  0  0  0  1  0  0  0
27     0  0  0  0  0  0  0  0  0  1
28     0  0  0  0  0  0  0  0  0  1
29     0  0  0  0  0  0  0  1  0  0
...   .. .. .. .. .. .. .. .. .. ..
41970  0  0  1  0  0  0  0  0  0  0
41971  0  0  0  1  0  0  0  0  0  0
41972  0  0  0  0  1  0  0  0  0  0
41973  0  0  0  0  1  0  0  0  0  0
41974  0  0  0  1  0  0  0  0  0  0
41975  0  0  0  0  0  0  0  0  0  1
41976  0  0  1  0  0  0  0  0  0  0
41977  0  0  0  0  1  0  0  0  0  0
41978  0  0  0  0  1  0  0  0  0  0
41979  0  0  0  0  1  0  0  0  0  0
41980  0  0  0  0  0  0  0  1  0  0
41981  0  0  1  0  0  0  0  0  0  0
41982  0  0  0  0  0  0  0  0  1  0
41983  0  0  0  0  0  0  0  1  0  0
41984  0  0  0  1  0  0  0  0  0  0
41985  0  0  0  1  0  0  0  0  0  0
41986  1  0  0  0  0  0  0  0  0  0
41987  0  0  0  0  0  1  0  0  0  0
41988  1  0  0  0  0  0  0  0  0  0
41989  0  0  0  0  0  1  0  0  0  0
41990  0  0  0  1  0  0  0  0  0  0
41991  0  1  0  0  0  0  0  0  0  0
41992  0  0  0  0  0  0  0  0  0  1
41993  0  0  0  0  0  0  1  0  0  0
41994  0  0  0  0  1  0  0  0  0  0
41995  1  0  0  0  0  0  0  0  0  0
41996  0  1  0  0  0  0  0  0  0  0
41997  0  0  0  0  0  0  0  1  0  0
41998  0  0  0  0  0  0  1  0  0  0
41999  0  0  0  0  0  0  0  0  0  1

[42000 rows x 10 columns]

cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
cost : nan
정확도:0.017
