In [ ]:
#우리의 mnist 해결 mechanism


#train data를 이용해서 해당 모델을 학습
#결국 얻을려는건 H 하이파시스

#H를 얻어내서 이걸 이용해서 예측(predict)가 가능 

##test data(입력 feature ) 가 들어감

#소프트맥스 취하면 

#H->[0.12,0.02,0.33,0.122,0.34]

# argmax가장큰값을 찾아내는것 index를 얻고

#이값을 입력 label의 argmax와 비교해서 잘맞으면 예측이 잘되었다 

#결국 랜덤값으로 실행하는거라 운에 좌지우지

#그래서 결국 여러모델을 만들어서 결과를 취합



#### 앙상블

#기법으로 모델을 여러개만듬 리스트던 배열이던

#각각의 모델을 학습 
#각 모델에 입력 parameter(이미지 픽셀) 을 넣어서 예측값 알아냄
#model 1 -> [0.1,0.4]
#model 2 -> [0.2,0.5]
#..
#model 10

#각 열을 더함


#그래서 클레스와 인스턴스를 이용




In [5]:
import tensorflow as tf

class Student:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,kor,eng,math):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.kor=kor
        self.eng=eng
        self.math=math
    
    def calc_avg(self):
        return (self.kor+self.eng+self.math)/3
stu1=Student("홍길동",10,20,30)
print(stu1.calc_avg())

stu2=Student("김길동",10,20,30)
print(stu2.calc_avg())




20.0


NameError: name 'name' is not defined

In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]



class cnnmodel:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,sess):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.sess=sess
    def cost(self,train1,df4):
        n=0
        n1=100
        n2=100
        for step in range(10):
            num_of_iter = 42000

            n=0
            n1=100
            n2=100

            for i in range(420):


                batch_x = train1[n:n2]
                batch_y = df4[n:n2]
                _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

                n=n+n1
                n2=n2+n1

            print("cost : {}".format(cost_val))

    def study(train1,train2):
        df1=pd.DataFrame()
        df2=pd.DataFrame()
        df4=pd.DataFrame()

        arr = np.zeros((10,10), dtype=np.int32)
        df1=arr

        for n in range(0,10):

            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(train2))


        for n in range(0,tr2):

            df2[n]=df1[train2[n]]

        df4=df2.transpose()

        number=int(len(train1)*2/3)


        train1_1=train1[0:number]
        train1_test=train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]


        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        L2=tf.reshape(L2,shape=[-1,7*7*64])

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)

        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )
        H = tf.matmul(layer2,W4)+b4
        
        cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

        train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

        sess=tf.Session()
        sess.run(tf.global_variables_initializer())
        return H
    

predict = tf.argmax(H,1)
correct=tf.equal(predict , tf.argmax(Y,1)) 

accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

yy_value=pd.DataFrame(columns=["ImageId","Label"])




In [ ]:
import tensorflow as tf

class cnnmodel:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,kor,eng,math):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.kor=kor
        self.eng=eng
        self.math=math
    
    def create_network(self)
        return (self.kor+self.eng+self.math)/3
stu1=Student("홍길동",10,20,30)
print(stu1.calc_avg())

stu2=Student("김길동",10,20,30)
print(stu2.calc_avg())

In [22]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]



class cnnmodel:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,sess):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.sess=sess
        
    def onehot(self):
        df1=pd.DataFrame()
        df2=pd.DataFrame()
        df4=pd.DataFrame()
        
        arr = np.zeros((10,10), dtype=np.int32)
        df1=arr
        
        for n in range(0,10):
            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(train2))


        for n in range(0,tr2):
            df2[n]=df1[train2[n]]

        df4=df2.transpose()
        return df4
    def train_test(self,train1,df4):
    
        number=int(len(train1)*2/3)

        train1_1=train1[0:number]
        train1_test=train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]
        
        return df4_1 # , , , 
        
    def Layer1(self):
    
        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        L2=tf.reshape(L2,shape=[-1,7*7*64])
        
        return L2
    
    
    def wbh(self):

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )
        H = tf.matmul(layer2,W4)+b4

        return H
    

# cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

# train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

# sess=tf.Session()
# sess.run(tf.global_variables_initializer())


# n=0
# n1=100
# n2=100

# print(int(nn))

# for step in range(10):
#     num_of_iter = 42000
    
#     n=0
#     n1=100
#     n2=100
    
#     for i in range(420):
        
        
#         batch_x = train1[n:n2]
#         batch_y = df4[n:n2]
#         _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

#         n=n+n1
#         n2=n2+n1
        
#     print("cost : {}".format(cost_val))
    

# predict = tf.argmax(H,1)
# correct=tf.equal(predict , tf.argmax(Y,1)) 

# accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

# yy_value=pd.DataFrame(columns=["ImageId","Label"])
  
    
    
    def Label(self):

        n=0
        n1=100
        n2=100
        a=[]

        for i in range(280):
            batch_x=test[n:n2]

            #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
            a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))
            

        yy_value["Label"]=a
        
        return yy_value
    def image(self):

        nnn=[]
        for nnnn in range(1,28001):
            nnn.append(nnnn)

        yy_value["ImageId"]=nnn
        print(yy_value)

        return yy_value
    
    def save(self):
        yy_value.to_csv("./data/submit_mnist", index=False)

    def testdata(self):
    

        n=0
        n1=100
        n2=100
        for i in range(140):
            batch_x=train1_test[n:n2]
            batch_y =df4_test[n:n2]
            correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
            result_sum += correct_num
            n=n+n1
            n2=n2+n1
        
        print("정확도:{}".format(result_sum/14000))
    
#for n in range(10)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
cnn=cnnmodel("model",sess)
    
#display(cnn.train_test(train1,cnn.onehot()))

display(cnn.train_test(train1,cnn.onehot()))



0  1  2  3  4  5  6  7  8  9
0      0  1  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  1  0  0  0  0  0  0  0  0
3      0  0  0  0  1  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0
5      1  0  0  0  0  0  0  0  0  0
6      0  0  0  0  0  0  0  1  0  0
7      0  0  0  1  0  0  0  0  0  0
8      0  0  0  0  0  1  0  0  0  0
9      0  0  0  1  0  0  0  0  0  0
10     0  0  0  0  0  0  0  0  1  0
11     0  0  0  0  0  0  0  0  0  1
12     0  1  0  0  0  0  0  0  0  0
13     0  0  0  1  0  0  0  0  0  0
14     0  0  0  1  0  0  0  0  0  0
15     0  1  0  0  0  0  0  0  0  0
16     0  0  1  0  0  0  0  0  0  0
17     1  0  0  0  0  0  0  0  0  0
18     0  0  0  0  0  0  0  1  0  0
19     0  0  0  0  0  1  0  0  0  0
20     0  0  0  0  0  0  0  0  1  0
21     0  0  0  0  0  0  1  0  0  0
22     0  0  1  0  0  0  0  0  0  0
23     1  0  0  0  0  0  0  0  0  0
24     0  0  1  0  0  0  0  0  0  0
25     0  0  0  1  0  0  0  0  0  0
26     0  0  0  0  0  0  1  0  0  0
27     0  0  0  0  0  0  0  0  0  1
28     0  0  0  0  0  0  0  0  0  1
29     0  0  0  0  0  0  0  1  0  0
...   .. .. .. .. .. .. .. .. .. ..
27970  0  0  1  0  0  0  0  0  0  0
27971  0  0  1  0  0  0  0  0  0  0
27972  1  0  0  0  0  0  0  0  0  0
27973  0  0  0  0  1  0  0  0  0  0
27974  1  0  0  0  0  0  0  0  0  0
27975  0  1  0  0  0  0  0  0  0  0
27976  1  0  0  0  0  0  0  0  0  0
27977  0  0  0  0  0  0  1  0  0  0
27978  0  1  0  0  0  0  0  0  0  0
27979  1  0  0  0  0  0  0  0  0  0
27980  0  0  0  0  0  0  0  0  0  1
27981  0  0  0  0  0  0  0  0  1  0
27982  0  1  0  0  0  0  0  0  0  0
27983  1  0  0  0  0  0  0  0  0  0
27984  0  1  0  0  0  0  0  0  0  0
27985  0  0  0  0  0  0  0  0  1  0
27986  1  0  0  0  0  0  0  0  0  0
27987  0  0  0  0  0  0  0  0  0  1
27988  0  0  1  0  0  0  0  0  0  0
27989  0  0  0  0  0  0  0  0  1  0
27990  0  0  0  0  0  0  1  0  0  0
27991  0  0  0  0  0  0  0  1  0  0
27992  0  0  0  0  0  0  1  0  0  0
27993  0  0  0  1  0  0  0  0  0  0
27994  0  0  0  0  0  0  1  0  0  0
27995  0  0  0  0  0  0  1  0  0  0
27996  1  0  0  0  0  0  0  0  0  0
27997  0  0  0  0  0  0  0  0  1  0
27998  1  0  0  0  0  0  0  0  0  0
27999  0  0  0  0  0  0  0  1  0  0

[28000 rows x 10 columns]

In [ ]:
# import tensorflow as tf
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]

nn=int(len(train1))

X=tf.placeholder(shape=[None,784], dtype=tf.float32)
Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지


df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)

df1=arr

df2=pd.DataFrame()


for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):
    df2[n]=df1[train2[n]]

df4=pd.DataFrame()

df4=df2.transpose()





number=int(len(train1)*2/3)

train1_1=train1[0:number]
train1_test=train1[number:-1]

df4_1=df4[0:number]
df4_test=df4[number:-1]







X_img = tf.reshape(X, shape=[-1,28,28,1])

W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

L1 = tf.nn.relu(L1)
p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)



L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

#########CONVOLUTION LAYER 끝

#4. NURAL NETWORK

L2=tf.reshape(L2,shape=[-1,7*7*64])

#print(L2.shape)

# 5. weight & bias

W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
b2=tf.Variable(tf.random_normal([256]),name="bias2" )

_layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
b3=tf.Variable(tf.random_normal([256]),name="bias3" )

_layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
b4=tf.Variable(tf.random_normal([10]),name="bias4" )

# hypothesis 가설만들어야함


H = tf.matmul(layer2,W4)+b4

#cost 함수

cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

#학습

num_of_epoch = 10
batch_size=100

display(train1)
display(df4)


n=0
n1=100
n2=100

print(int(nn))
for step in range(10):
    num_of_iter = 42000
    
    n=0
    n1=100
    n2=100
    
    for i in range(420):
        
        
        batch_x = train1[n:n2]
        batch_y = df4[n:n2]
        _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

        n=n+n1
        n2=n2+n1
        
        
        
        
        
    print("cost : {}".format(cost_val))
    
    
    

predict = tf.argmax(H,1)
correct=tf.equal(predict , tf.argmax(Y,1)) 

accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

result_sum=0
num_of_iter = int(num_of_iter/100)



### 라벨 뽑기 predict 이용
yy_value=pd.DataFrame(columns=["ImageId","Label"])


n=0
n1=100
n2=100

for i in range(280):
    batch_x=test[n:n2]
    
    yy_value["Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
    
    n=n+n1
    n2=n2+n1

print(yy_value)
print("=========")


n=0
n1=100
n2=100
a=[]

for i in range(280):
    batch_x=test[n:n2]
    
    #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
    a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))
    

print("=========")

yy_value=pd.DataFrame(columns=["ImageId","Label"])

yy_value["Label"]=a

nnn=[]
for nnnn in range(1,28001):
    nnn.append(nnnn)

yy_value["ImageId"]=nnn
print(yy_value)


yy_value.to_csv("./data/submit_mnist", index=False)


###테스트

# yy_value=sess.run(predict , feed_dict={X:test,keep_rate:1})

# dfff=pd.DataFrame(columns=["ImageId","Label"])
# dfff["label"]=yy_value
# arr=[]
# for dfffnum in range(0,len(dfff)):
#     arr=dfffnum

# print(dfffnum)



#=================


# n=0
# n1=100
# n2=100
# for i in range(140):
#     batch_x=train1_test[n:n2]
#     batch_y =df4_test[n:n2]
#     correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
#     result_sum += correct_num
#     n=n+n1
#     n2=n2+n1
    
    
# #tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
# #print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

# print("정확도:{}".format(result_sum/14000))


In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]



class cnnmodel:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,sess):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.sess=sess
        
    def onehot(self):
        df1=pd.DataFrame()
        df2=pd.DataFrame()
        df4=pd.DataFrame()
        
        arr = np.zeros((10,10), dtype=np.int32)
        df1=arr
        
        for n in range(0,10):
            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(train2))


        for n in range(0,tr2):
            df2[n]=df1[train2[n]]

        df4=df2.transpose()
        return df4
    def train_test(self,train1,df4):
    
        number=int(len(train1)*2/3)

        train1_1=train1[0:number]
        train1_test=train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]
        
        return df4_1 # , , , 
        
    def Layer1(self):
    
        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        L2=tf.reshape(L2,shape=[-1,7*7*64])
        
        return L2
    
    
    def wbh(self):

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )
        H = tf.matmul(layer2,W4)+b4

        return H
    

# cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

# train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

# sess=tf.Session()
# sess.run(tf.global_variables_initializer())


# n=0
# n1=100
# n2=100

# print(int(nn))

# for step in range(10):
#     num_of_iter = 42000
    
#     n=0
#     n1=100
#     n2=100
    
#     for i in range(420):
        
        
#         batch_x = train1[n:n2]
#         batch_y = df4[n:n2]
#         _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

#         n=n+n1
#         n2=n2+n1
        
#     print("cost : {}".format(cost_val))
    

# predict = tf.argmax(H,1)
# correct=tf.equal(predict , tf.argmax(Y,1)) 

# accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

# yy_value=pd.DataFrame(columns=["ImageId","Label"])
  
    
    
    def Label(self):

        n=0
        n1=100
        n2=100
        a=[]

        for i in range(280):
            batch_x=test[n:n2]

            #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
            a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))
            

        yy_value["Label"]=a
        
        return yy_value
    def image(self):

        nnn=[]
        for nnnn in range(1,28001):
            nnn.append(nnnn)

        yy_value["ImageId"]=nnn
        print(yy_value)

        return yy_value
    
    def save(self):
        yy_value.to_csv("./data/submit_mnist", index=False)

    def testdata(self):
    

        n=0
        n1=100
        n2=100
        for i in range(140):
            batch_x=train1_test[n:n2]
            batch_y =df4_test[n:n2]
            correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
            result_sum += correct_num
            n=n+n1
            n2=n2+n1
        
        print("정확도:{}".format(result_sum/14000))
    
#for n in range(10)
sess=tf.Session()
sess.run(tf.global_variables_initializer())
cnn=cnnmodel("model",sess)
    
#display(cnn.train_test(train1,cnn.onehot()))

display(cnn.train_test(train1,cnn.onehot()))


In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]


class cnnmodel:   
    def __init__(self,name,sess):  

        self.name=name  
        self.sess=sess
        
    def model(self):
        nn=int(len(train1))

        X=tf.placeholder(shape=[None,784], dtype=tf.float32)
        Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

        keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지


        df1=pd.DataFrame()
        arr = np.zeros((10,10), dtype=np.int32)

        df1=arr

        df2=pd.DataFrame()


        for n in range(0,10):
            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(train2))


        for n in range(0,tr2):
            df2[n]=df1[train2[n]]

        df4=pd.DataFrame()

        df4=df2.transpose()


        number=int(len(train1)*2/3)

        train1_1=train1[0:number]
        train1_test=train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]







        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)



        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        #########CONVOLUTION LAYER 끝

        #4. NURAL NETWORK

        L2=tf.reshape(L2,shape=[-1,7*7*64])

        #print(L2.shape)

        # 5. weight & bias

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )

        # hypothesis 가설만들어야함


        H = tf.matmul(layer2,W4)+b4

        #cost 함수

        cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

        train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

        sess=tf.Session()
        sess.run(tf.global_variables_initializer())

        #학습

        num_of_epoch = 10
        batch_size=100

        display(train1)
        display(df4)


        n=0
        n1=100
        n2=100

        print(int(nn))
        for step in range(10):
            num_of_iter = 42000

            n=0
            n1=100
            n2=100

            for i in range(420):


                batch_x = train1[n:n2]
                batch_y = df4[n:n2]
                _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

                n=n+n1
                n2=n2+n1





            print("cost : {}".format(cost_val))




        predict = tf.argmax(H,1)
        correct=tf.equal(predict , tf.argmax(Y,1)) 

        accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

        result_sum=0
        num_of_iter = int(num_of_iter/100)



        ### 라벨 뽑기 predict 이용
        yy_value=pd.DataFrame(columns=["ImageId","Label"])


        n=0
        n1=100
        n2=100

        for i in range(280):
            batch_x=test[n:n2]

            yy_value["Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})

            n=n+n1
            n2=n2+n1

        print(yy_value)
        print("=========")


        n=0
        n1=100
        n2=100
        a=[]

        for i in range(280):
            batch_x=test[n:n2]

            #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
            a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))


        print("=========")

        yy_value=pd.DataFrame(columns=["ImageId","Label"])

        yy_value["Label"]=a

        nnn=[]
        for nnnn in range(1,28001):
            nnn.append(nnnn)

        yy_value["ImageId"]=nnn
        print(yy_value)


        yy_value.to_csv("./data/submit_mnist", index=False)


        ###테스트

        # yy_value=sess.run(predict , feed_dict={X:test,keep_rate:1})

        # dfff=pd.DataFrame(columns=["ImageId","Label"])
        # dfff["label"]=yy_value
        # arr=[]
        # for dfffnum in range(0,len(dfff)):
        #     arr=dfffnum

        # print(dfffnum)



        #=================


        # n=0
        # n1=100
        # n2=100
        # for i in range(140):
        #     batch_x=train1_test[n:n2]
        #     batch_y =df4_test[n:n2]
        #     correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
        #     result_sum += correct_num
        #     n=n+n1
        #     n2=n2+n1


        # #tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
        # #print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

        # print("정확도:{}".format(result_sum/14000))
        



stu1=Student("홍길동",10,20,30)
print(stu1.calc_avg())

stu2=Student("김길동",10,20,30)
print(stu2.calc_avg())

In [30]:

import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]


class cnnmodel:   
    def __init__(self,name):  

        self.name=name  
       
        
    def model(self):
        nn=int(len(train1))

        X=tf.placeholder(shape=[None,784], dtype=tf.float32)
        Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

        keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지


        df1=pd.DataFrame()
        arr = np.zeros((10,10), dtype=np.int32)

        df1=arr

        df2=pd.DataFrame()


        for n in range(0,10):
            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(train2))


        for n in range(0,tr2):
            df2[n]=df1[train2[n]]

        df4=pd.DataFrame()

        df4=df2.transpose()


        number=int(len(train1)*2/3)

        train1_1=train1[0:number]
        train1_test=train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]







        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)



        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        #########CONVOLUTION LAYER 끝

        #4. NURAL NETWORK

        L2=tf.reshape(L2,shape=[-1,7*7*64])

        #print(L2.shape)

        # 5. weight & bias

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )

        # hypothesis 가설만들어야함


        H = tf.matmul(layer2,W4)+b4

        #cost 함수

        cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

        train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

        sess=tf.Session()
        sess.run(tf.global_variables_initializer())

        #학습

        num_of_epoch = 10
        batch_size=100


        n=0
        n1=100
        n2=100

        
        for step in range(10):
            num_of_iter = 42000

            n=0
            n1=100
            n2=100

            for i in range(420):


                batch_x = train1[n:n2]
                batch_y = df4[n:n2]
                _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

                n=n+n1
                n2=n2+n1





            print("cost : {}".format(cost_val))




        predict = tf.argmax(H,1)
        correct=tf.equal(predict , tf.argmax(Y,1)) 

        accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))
        
        n=0
        n1=100
        n2=100
        y=[]
        for i in range(420):

            batch_x=test[n:n2]

            yyy=sess.run(ac, feed_dict={X:batch_x,keep_rate:1})

            n=n+n1
            n2=n2+n1

        print(yyy)
        
        return yyy

    
cnn=cnnmodel("model1")
yyy=cnn.model()
print(yyy)


          #### 샘플데이터 양식 만들기
        ### 라벨 뽑기 predict 이용
#         yy_value=pd.DataFrame(columns=["ImageId","Label"])


#         n=0
#         n1=100
#         n2=100

#         for i in range(280):
#             batch_x=test[n:n2]

#             yy_value["Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})

#             n=n+n1
#             n2=n2+n1

#         print(yy_value)
#         print("=========")

     
        
        
#         n=0
#         n1=100
#         n2=100
#         a=[]

#         for i in range(280):
#             batch_x=test[n:n2]

#             #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
#             a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))


#         print("=========")

#         yy_value=pd.DataFrame(columns=["ImageId","Label"])

#         yy_value["Label"]=a

#         nnn=[]
#         for nnnn in range(1,28001):
#             nnn.append(nnnn)

#         yy_value["ImageId"]=nnn
#         print(yy_value)


        
        
        
        
        ###저장
        #yy_value.to_csv("./data/submit_mnist", index=False)


        ###테스트

        # yy_value=sess.run(predict , feed_dict={X:test,keep_rate:1})

        # dfff=pd.DataFrame(columns=["ImageId","Label"])
        # dfff["label"]=yy_value
        # arr=[]
        # for dfffnum in range(0,len(dfff)):
        #     arr=dfffnum

        # print(dfffnum)



        #=================


        # n=0
        # n1=100
        # n2=100
        # for i in range(140):
        #     batch_x=train1_test[n:n2]
        #     batch_y =df4_test[n:n2]
        #     correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
        #     result_sum += correct_num
        #     n=n+n1
        #     n2=n2+n1


        # #tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
        # #print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

        # print("정확도:{}".format(result_sum/14000))
        




cost : 0.3071288466453552
cost : 0.3279969096183777
cost : 0.18736927211284637
cost : 0.18291230499744415
cost : 0.160679429769516
cost : 0.3759686350822449
cost : 0.2836356461048126
cost : 0.1708727478981018
cost : 0.2695407271385193
cost : 0.18917755782604218


ValueError: Fetch argument <tf.Tensor 'Sum:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("Sum:0", shape=(), dtype=float32) is not an element of this graph.)

In [14]:
# 원핫 인코딩 방법들 


import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings


df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)

df1=arr

df2=pd.DataFrame()


for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):
    df2[n]=df1[train2[n]]

df4=pd.DataFrame()

df4=df2.transpose()







indices = [0, 1, 2,3,4,5,6,7,8,9]
depth = 10
one_hot2=tf.one_hot(indices, depth)  # output: [3 x 3]
sess = tf.Session()
print(sess.run(one_hot2))

one_hot3=sess.run(one_hot2)

display(one_hot3)

df=pd.DataFrame({"번호":[0,1,2,3,4,5,6,7,8,9]})
#music_dummy_mat = pd.get_dummies(music_df['music_genre'])

print(df)
df_dummy_mat = pd.get_dummies(df["번호"])
display(df_dummy_mat)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

   번호
0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9


0  1  2  3  4  5  6  7  8  9
0  1  0  0  0  0  0  0  0  0  0
1  0  1  0  0  0  0  0  0  0  0
2  0  0  1  0  0  0  0  0  0  0
3  0  0  0  1  0  0  0  0  0  0
4  0  0  0  0  1  0  0  0  0  0
5  0  0  0  0  0  1  0  0  0  0
6  0  0  0  0  0  0  1  0  0  0
7  0  0  0  0  0  0  0  1  0  0
8  0  0  0  0  0  0  0  0  1  0
9  0  0  0  0  0  0  0  0  0  1

In [ ]:
# 클레스 = 틀

# 틀에 맞춰서 일정공간 메모리 확보하는놈이 인스턴스 

# 각 모델을 클레스의 인스턴스로 만들어서 관리

# 우리가 만들 model의 데이터와 기능을 생각해서 클레스를


In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]


class CNNModel:
    
    
    ###기능나열
    #모델구축
    #학습
    #정확도
    #예측값
    
    def __init__(self,sess,name,train1,train2)   #정해진 이름 클레스의 인스턴스를 만들때 가장먼저실행 생성자 
                                    #초기값에 파라미터를 받게됨
        self.sess=sess
        self.name=name # 전달받을 name(지역변수)이 앞에 self.name(객체변수)은 객체내에서 사용하는 데이터 
        self.train1=train1 #객체가 사용하는 데이터
        self.train2=train2
    def build(self):       #train1, train2
        
        df1=pd.DataFrame()
        df2=pd.DataFrame()
        df4=pd.DataFrame()

        arr = np.zeros((10,10), dtype=np.int32)
        df1=arr

        for n in range(0,10):

            df1[n,n]=1
            df2[n]=np.arange(10)

        tr2=int(len(self.train2))


        for n in range(0,tr2):

            df2[n]=df1[self.train2[n]]

        df4=df2.transpose()  #y_data

        number=int(len(train1)*2/3)


        train1_1=self.train1[0:number]
        train1_test=self.train1[number:-1]

        df4_1=df4[0:number]
        df4_test=df4[number:-1]


        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        L2=tf.reshape(L2,shape=[-1,7*7*64])

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)

        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )
        H = tf.matmul(layer2,W4)+b4
        
        cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))

        train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)
        sess=tf.Session()
        sess.run(tf.global_variables_initializer())
        
        return H
        
        
        
        
    def study(self)
        self.sess.run([self.train.cost],feed_dict=[X:x_data,Y:y_data])
        n=0
        n1=100
        n2=100

        print(int(nn))
        for step in range(10):
            num_of_iter = 42000

            n=0
            n1=100
            n2=100

            for i in range(420):


                batch_x = self.train1[n:n2]
                batch_y = df4[n:n2]
                _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

                n=n+n1
                n2=n2+n1
        
            print("cost : {}".format(cost_val))
        
        
    def Predict(self,H):
        predict = tf.argmax(H,1)
        
        return predict
    def Correct(self,predict):   
        correct=tf.equal(predict , tf.argmax(Y,1)) 
        return correct
    def Accuracy(self,correct):
        accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))
        return accuracy
    

모델객체 생성    
# model = CNNModel("model1".sess)
# model1.build()
# model1.exec_train(x_data)


models=[]
num_models=10

models.append(CNNModel(sess,model0))

for m in range(num_models):
    models.append(CNNModel(sess,"model"+str(m)))

    

models.build()
models.exec_train(x_data)
sess.run(tf.global_variables_initializer())



#학습

In [44]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")

train1=train.drop("label", axis=1, inplace=False) #x_data
train2=train["label"]
df1=pd.DataFrame()
df2=pd.DataFrame()
df4=pd.DataFrame()

arr = np.zeros((10,10), dtype=np.int32)
df1=arr

for n in range(0,10):

    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):

    df2[n]=df1[train2[n]]

df4=df2.transpose()  #y_data




class CNNModel:
    
    
    ###기능나열
    #모델구축
    #학습
    #정확도
    #예측값
    
    def __init__(self,sess,name,train1,df4):   #정해진 이름 클레스의 인스턴스를 만들때 가장먼저실행 생성자 
                                    #초기값에 파라미터를 받게됨
        self.sess=sess
        self.name=name # 전달받을 name(지역변수)이 앞에 self.name(객체변수)은 객체내에서 사용하는 데이터 
        self.train1=train1 #객체가 사용하는 데이터
        self.df4=df4
    def Build(self):       #train1, train2
        
        
        X=tf.placeholder(shape=[None,784], dtype=tf.float32)
        Y=tf.placeholder(shape=[None,10], dtype=tf.float32)
        X_img = tf.reshape(X, shape=[-1,28,28,1])

        W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

        L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

        L1 = tf.nn.relu(L1)
        p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

        L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

        L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

        L2=tf.reshape(L2,shape=[-1,7*7*64])

        W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
        b2=tf.Variable(tf.random_normal([256]),name="bias2" )

        _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
        layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)

        W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
        b3=tf.Variable(tf.random_normal([256]),name="bias3" )

        _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
        layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


        W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
        b4=tf.Variable(tf.random_normal([10]),name="bias4" )
        
        
        self.H = tf.matmul(layer2,W4)+b4
        
        self.cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.H , labels=Y))

        self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)
        
        self.predict = tf.argmax(self.H,1)
        self.correct=tf.equal(self.predict , tf.argmax(Y,1)) 
        self.accuracy=tf.reduce_sum(tf.cast(self.correct , dtype=tf.float32))
        
        
    def Train(self):
        sess.run(tf.global_variables_initializer())
        keep_rate=tf.placeholder(dtype=tf.float32)
        n=0
        n1=100
        n2=100

        for step in range(10):
            num_of_iter = 42000

            n=0
            n1=100
            n2=100

            for i in range(420):


                batch_x = self.train1[n:n2]
                batch_y = self.df4[n:n2]
                _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.7})

                n=n+n1
                n2=n2+n1
        
            print("cost : {}".format(cost_val))
            
        
#    def predict(self):
       
        

#모델객체 생성    
# model = CNNModel("model1".sess)
# model1.build()
# model1.exec_train(x_data)


#models=[]
#models.append


# num_models=10



# for m in range(num_models):
#     models.append(CNNModel(sess,"model"+str(m),train1,df4))

#print(CNNModel(sess,"model0",train1,df4).Train())    #H값 나오고
#H2=CNNModel(sess,"model0",train1,df4).Train()

print(H2)

m1=CNNModel(sess,"model0",train1,df4)


print(m1.Train())

# sess = tf.Session()
# H2=np.array
# print(sess.run([H2],feed_dict={X:H1}))
#models.exec_train(x_data)




#학습

None


ValueError: Fetch argument <tf.Operation 'init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init"
op: "NoOp"
 is not an element of this graph.)

In [ ]:
import tensorflow as tf

class Student:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,kor,eng,math):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.kor=kor
        self.eng=eng
        self.math=math
    
    def calc_avg(self):
        return (self.kor+self.eng+self.math)/3
stu1=Student("홍길동",10,20,30)
print(stu1.calc_avg())

stu2=Student("김길동",10,20,30)
print(stu2.calc_avg())


def __init__(self,sess,name,train1,df4)

In [32]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")

X=tf.placeholder(shape=[None,784], dtype=tf.float32)
Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

train1=train.drop("label", axis=1, inplace=False) #x_data
train2=train["label"]
df1=pd.DataFrame()
df2=pd.DataFrame()
df4=pd.DataFrame()

arr = np.zeros((10,10), dtype=np.int32)
df1=arr

for n in range(0,10):

    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):

    df2[n]=df1[train2[n]]

df4=df2.transpose()  #y_data
keep_rate=tf.placeholder(dtype=tf.float32)
keep_rate=0.5

print(train1)

       pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       

In [ ]:
import tensorflow as tf

class Student:   #클레스 
    # 언더바 2개가 뭘 의미한댔지?
    def __init__(self,name,kor,eng,math):       # self-> 자바에서 this 함수이기때문에 arg 리스트가 나옴

        self.name=name  # 객체가 존재하는한 계속해서 남아있는 객체  자기가 가지고 있는
        self.kor=kor
        self.eng=eng
        self.math=math
    
    def calc_avg(self):
        return (self.kor+self.eng+self.math)/3
stu1=Student("홍길동",10,20,30)
print(stu1.calc_avg())

stu2=Student("김길동",10,20,30)
print(stu2.calc_avg())


def __init__(self,sess,name,train1,df4)

In [ ]:
# import tensorflow as tf
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


train1=train.drop("label", axis=1, inplace=False)
train2=train["label"]

X=tf.placeholder(shape=[None,784], dtype=tf.float32)
Y=tf.placeholder(shape=[None,10], dtype=tf.float32)

keep_rate=tf.placeholder(dtype=tf.float32)  #드랍아웃에서 얼마나 살릴지


df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)

df1=arr

df2=pd.DataFrame()


for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))


for n in range(0,tr2):
    df2[n]=df1[train2[n]]

df4=pd.DataFrame()

df4=df2.transpose()


number=int(len(train1)*2/3)

train1_1=train1[0:number]
train1_test=train1[number:-1]

df4_1=df4[0:number]
df4_test=df4[number:-1]


X_img = tf.reshape(X, shape=[-1,28,28,1])

W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

L1 = tf.nn.relu(L1)
p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

L2=tf.reshape(L2,shape=[-1,7*7*64])

W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
b2=tf.Variable(tf.random_normal([256]),name="bias2" )

_layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
layer1 = tf.nn.dropout(_layer1 , keep_prob=keep_rate)


W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
b3=tf.Variable(tf.random_normal([256]),name="bias3" )

_layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
layer2 = tf.nn.dropout(_layer2 , keep_prob=keep_rate)


W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
b4=tf.Variable(tf.random_normal([10]),name="bias4" )

# hypothesis 가설만들어야함


H = tf.matmul(layer2,W4)+b4

#cost 함수

cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=H , labels=Y))



number=0
float(number)



train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(cost)





sess=tf.Session()
sess.run(tf.global_variables_initializer())

#학습

num_of_epoch = 10
batch_size=100



n=0
n1=100
n2=100


for step in range(10):
    num_of_iter = 42000
    print(step)
    n=0
    n1=100
    n2=100

    for i in range(420):


        batch_x = train1[n:n2]
        batch_y = df4[n:n2]
        _,cost_val=sess.run([train,cost], feed_dict={X:batch_x , Y:batch_y ,keep_rate:0.5
                                                    })

        n=n+n1
        n2=n2+n1





    print("cost : {}".format(cost_val))




predict = tf.argmax(H,1)
correct=tf.equal(predict , tf.argmax(Y,1)) 

accuracy=tf.reduce_sum(tf.cast(correct , dtype=tf.float32))

result_sum=0
num_of_iter = int(num_of_iter/100)



### 라벨 뽑기 predict 이용


yy_value=pd.DataFrame(columns=["ImageId","Label"])


# n=0
# n1=100
# n2=100

# for i in range(280):
#     batch_x=test[n:n2]

#     yy_value["Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})

#     n=n+n1
#     n2=n2+n1

# print(yy_value)
# print("=========")


n=0
n1=100
n2=100
a=[]

for i in range(280):
    batch_x=test[n:n2]

    #yy_value.loc[n:n2,"Label"]=sess.run(predict, feed_dict={X:batch_x,keep_rate:1})
    a.extend(sess.run(predict, feed_dict={X:batch_x,keep_rate:1}))
    
    n=n+n1
    n2=n2+n1

print("=========")

yy_value=pd.DataFrame(columns=["ImageId","Label"])

yy_value["Label"]=a

nnn=[]
for nnnn in range(1,28001):
    nnn.append(nnnn)

yy_value["ImageId"]=nnn
print(yy_value)


yy_value.to_csv("./data/submit_mnistwow", index=False)




# yy_value=sess.run(predict , feed_dict={X:test,keep_rate:1})

# dfff=pd.DataFrame(columns=["ImageId","Label"])
# dfff["label"]=yy_value
# arr=[]
# for dfffnum in range(0,len(dfff)):
#     arr=dfffnum

# print(dfffnum)



###테스트



n=0
n1=100
n2=100
for i in range(140):
    batch_x=train1_test[n:n2]
    batch_y =df4_test[n:n2]
    correct_num=sess.run(accuracy, feed_dict={X:batch_x , Y:batch_y ,keep_rate:1})
    result_sum += correct_num
    n=n+n1
    n2=n2+n1


#tf.cast(correct , dtype=tf.float32# 맞으면 1 틀리면 0 100개를 끌어왔는데 반은맞고 반은 틀리면 50이됨 
#print("정확도:{}".format(sess.run(accuracy, feed_dict={X:mnist.test.images,Y:mnist.test.labels,keep_rate:1})) )

print("{}번째: , 정확도:{}".format(number,result_sum/14000))
