In [19]:
# import tensorflow as tf
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

## reset tensorflow graph
tf.reset_default_graph()

class CNNModel: 
    
    def __init__(self,sess,name):     

        self.sess=sess
        self.name=name 
        
    def build_graph(self):
        with tf.variable_scope(self.name):
            self.X=tf.placeholder(shape=[None,784], dtype=tf.float32)
            self.Y=tf.placeholder(shape=[None,10], dtype=tf.float32)
            self.keep_rate=tf.placeholder(dtype=tf.float32) 
            
            X_img = tf.reshape(self.X, shape=[-1,28,28,1])

            W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

            L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

            L1 = tf.nn.relu(L1)
            p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

            L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

            L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

            L2=tf.reshape(L2,shape=[-1,7*7*64])

            W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
            b2=tf.Variable(tf.random_normal([256]),name="bias2" )

            _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
            layer1 = tf.nn.dropout(_layer1 , keep_prob=self.keep_rate)


            W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
            b3=tf.Variable(tf.random_normal([256]),name="bias3" )

            _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
            layer2 = tf.nn.dropout(_layer2 , keep_prob=self.keep_rate)


            W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
            b4=tf.Variable(tf.random_normal([10]),name="bias4" )

            self.H = tf.matmul(layer2,W4)+b4

            self.cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.H , labels=self.Y))

            self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)

            self.predict = tf.argmax(self.H,1)
            self.correct=tf.equal(self.predict , tf.argmax(self.Y,1)) 

            self.accuracy=tf.reduce_sum(tf.cast(self.correct , dtype=tf.float32))

    
    def train_model(self,x,y,keep):
        
        _,cost_val=self.sess.run([self.train,self.cost], feed_dict={self.X:x , self.Y:y , self.keep_rate:keep})
        
            
    
    def H_value_sum(self,x,y):
        
        n=0
        n1=100
        n2=100
        H_zero = np.zeros((100,10),dtype=np.float32)
        dataindex_len=len(x_data)
        dataindex_len=int(dataindex_len/100)
        for num in range(10):
            ### 모델 10개
            model_list = ["m0","m1"]#,"m2","m3","m4","m5","m6","m7","m8","m9"]
            
            for k in model_list:
                batch_x = x[n:n2]
                batch_y = y[n:n2]
                H_val=(self.sess.run(self.H, feed_dict={self.X:batch_x , self.keep_rate:0.5 }))

                H_zero=H_zero+H_val
            
            self.H=H_zero/10
            print(self.H)

            n=n+n1
            n2=n2+n1
        return(self.H)

### x_data , y_data -> dataframe 형태
tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


x_data=train.drop("label", axis=1, inplace=False)
train2=train["label"]

 
df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)
df1=arr
df2=pd.DataFrame()
for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))
for n in range(0,tr2):
    df2[n]=df1[train2[n]]
y_data=pd.DataFrame()
y_data=df2.transpose()


x_data=x_data.values
y_data=y_data.values
### x_data , y_data -> dataframe 형태 -> 넘파이 어레이가 공통적으로 쓰임

###세션생성
sess=tf.Session()

###세션생성

###모델 생성
count_of_models = 2
models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
##모델 생성 끝

###세션 초기화 
sess.run(tf.global_variables_initializer())
###세션 초기화 끝


###학습
for num in range(count_of_models):
    models[num].build_graph()
    
    print(models[num])
    
    start_roof=0
    increase_roof=100
    finish_roof=100
    batch_size=100
    dataindex_len=len(x_data)
    traindataindex_len=int(dataindex_len/batch_size)
    
    print(traindataindex_len)
    H_zero = np.zeros((100,10),dtype=np.float32)
    n=0
    n1=100
    n2=100
    keep_rate=0.5
    
    for step in range(10):

        start_roof=0
        increase_roof=100
        finish_roof=100

        for i in range(traindataindex_len):
            batch_x = x_data[start_roof:finish_roof]
            batch_y = y_data[start_roof:finish_roof]
            models[num].train_model(batch_x , batch_y , keep_rate)
            start_roof=start_roof+increase_roof
            finish_roof=finish_roof+increase_roof

        print("cost : {}".format(cost_val))
##학습끝



FailedPreconditionError: Failed to allocate scratch buffer for device 0
	 [[{{node _SOURCE}} = NoOp[]()]]

In [1]:
# import tensorflow as tf
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

## reset tensorflow graph
tf.reset_default_graph()

class CNNModel: 
    
    def __init__(self,sess,name):     

        self.sess=sess
        self.name=name 
        
    def build_graph(self):
        with tf.variable_scope(self.name):
            self.X=tf.placeholder(shape=[None,784], dtype=tf.float32)
            self.Y=tf.placeholder(shape=[None,10], dtype=tf.float32)
            self.keep_rate=tf.placeholder(dtype=tf.float32) 
            
            X_img = tf.reshape(self.X, shape=[-1,28,28,1])

            W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

            L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

            L1 = tf.nn.relu(L1)
            p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

            L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

            L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

            L2=tf.reshape(L2,shape=[-1,7*7*64])

            W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
            b2=tf.Variable(tf.random_normal([256]),name="bias2" )

            _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
            layer1 = tf.nn.dropout(_layer1 , keep_prob=self.keep_rate)


            W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
            b3=tf.Variable(tf.random_normal([256]),name="bias3" )

            _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
            layer2 = tf.nn.dropout(_layer2 , keep_prob=self.keep_rate)


            W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
            b4=tf.Variable(tf.random_normal([10]),name="bias4" )

            self.H = tf.matmul(layer2,W4)+b4

            self.cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.H , labels=self.Y))

            self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)

            self.predict = tf.argmax(self.H,1)
            self.correct=tf.equal(self.predict , tf.argmax(self.Y,1)) 

            self.accuracy=tf.reduce_sum(tf.cast(self.correct , dtype=tf.float32))

    
    def train_model(self,x,y,keep):
        
        _,cost_val=self.sess.run([self.train,self.cost], feed_dict={self.X:x , self.Y:y , self.keep_rate:keep})
        
            
    
    def H_value_sum(self,x,y):
        
        n=0
        n1=100
        n2=100
        H_zero = np.zeros((100,10),dtype=np.float32)
        dataindex_len=len(x_data)
        dataindex_len=int(dataindex_len/100)
        for num in range(10):
            ### 모델 10개
            model_list = ["m0","m1"]#,"m2","m3","m4","m5","m6","m7","m8","m9"]
            
            for k in model_list:
                batch_x = x[n:n2]
                batch_y = y[n:n2]
                H_val=(self.sess.run(self.H, feed_dict={self.X:batch_x , self.keep_rate:0.5 }))

                H_zero=H_zero+H_val
            
            self.H=H_zero/10
            print(self.H)

            n=n+n1
            n2=n2+n1
        return(self.H)

### x_data , y_data -> dataframe 형태
tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


x_data=train.drop("label", axis=1, inplace=False)
train2=train["label"]

 
df1=pd.DataFrame()
df2=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)
df1=arr
for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))
for n in range(0,tr2):
    df2[n]=df1[train2[n]]
y_data=pd.DataFrame()
y_data=df2.transpose()


x_data=x_data.values
y_data=y_data.values
### x_data , y_data -> dataframe 형태 -> 넘파이 어레이가 공통적으로 쓰임

###세션생성
sess=tf.Session()

###세션생성

###모델 생성
count_of_models = 2
models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
##모델 생성 끝

print(models)


[<__main__.CNNModel object at 0x000000000F9B2978>, <__main__.CNNModel object at 0x000000000F9B2BA8>]


In [3]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

## reset tensorflow graph
tf.reset_default_graph()



### x_data , y_data -> dataframe 형태
tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


x_data=train.drop("label", axis=1, inplace=False)
train2=train["label"]

 
df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)
df1=arr
df2=pd.DataFrame()
for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))
for n in range(0,tr2):
    df2[n]=df1[train2[n]]
y_data=pd.DataFrame()
y_data=df2.transpose()

number=int(len(x_data)*2/3)

xtrain_data=x_data[0:number].values
xtext_data=x_data[number:-1].values

ytrain_data=y_data[0:number].values
ytest_data=y_data[number:-1].values
print("===============")
print(xtrain_data)
x_data=x_data.values
y_data=y_data.values


print("===============")

### x_data , y_data -> dataframe 형태 -> 넘파이 어레이가 공통적으로 쓰임
# display(x_data)
# print("============")
# display(y_data) #성공

#클레스 생성

class CNNModel: 
    
    def __init__(self,sess,name):     

        self.sess=sess
        self.name=name 
        self.build_graph()            # 해주고 안해주고 차이가 뭐지?
    def build_graph(self):
        with tf.variable_scope(self.name):
            self.X=tf.placeholder(shape=[None,784], dtype=tf.float32)
            self.Y=tf.placeholder(shape=[None,10], dtype=tf.float32)
            self.keep_rate=tf.placeholder(dtype=tf.float32) 
            
            X_img = tf.reshape(self.X, shape=[-1,28,28,1])

            W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

            L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

            L1 = tf.nn.relu(L1)
            p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

            L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

            L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

            L2=tf.reshape(L2,shape=[-1,7*7*64])

            W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
            b2=tf.Variable(tf.random_normal([256]),name="bias2" )

            _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
            layer1 = tf.nn.dropout(_layer1 , keep_prob=self.keep_rate)


            W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
            b3=tf.Variable(tf.random_normal([256]),name="bias3" )

            _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
            layer2 = tf.nn.dropout(_layer2 , keep_prob=self.keep_rate)


            W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
            b4=tf.Variable(tf.random_normal([10]),name="bias4" )

            self.H = tf.matmul(layer2,W4)+b4

            self.cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.H , labels=self.Y))

            self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)

            self.predict = tf.argmax(self.H,1)
            self.correct=tf.equal(self.predict , tf.argmax(self.Y,1)) 

            self.accuracy=tf.reduce_sum(tf.cast(self.correct , dtype=tf.float32))


    def train_model(self,x,y,keep):
        
        _,cost_val=self.sess.run([self.train,self.cost], feed_dict={self.X:x , self.Y:y , self.keep_rate:keep})
        return cost_val
    
    def ensemble_predict(self,x,keep):
        H_val = self.sess.run(self.H, feed_dict={self.X:x,self.keep_rate:keep})
        return H_val
sess = tf.Session()
sess.run(tf.global_variables_initializer())
count_of_models = 10
models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
keep_rate=0.5






#앙상블
for num1 in range(count_of_models):     # 10
    print(models[num1].build_graph)
    print("======")
    print(models[num1])
start_roof=0
increase_roof=100
finish_roof=100
batch_size=100
dataindex_len=len(x_data)  # 42000
traindataindex_len=int(dataindex_len/batch_size)  # 420


H_zero = np.zeros((100,10),dtype=np.float32)
print("모델이름: model{}".format(num1))
for num2 in range(traindataindex_len):   # 420
    batch_x = x_data[start_roof:finish_roof]
    batch_y = y_data[start_roof:finish_roof]

    for num3 in range(10):
        model_ensemble=models[num1].ensemble_predict(batch_x , keep_rate) # 앞수들 변수내용같은건 텐서플로 내에서 저장

        H_zero=H_zero+model_ensemble[num1]

        start_roof=start_roof+increase_roof
        finish_roof=finish_roof+increase_roof  
    ensemble_predict = tf.argmax(H_zero,1)
    ensemble_correct=tf.equal(ensemble_predict , tf.argmax(batch_y,1)) 

    ensemble_accuracy=tf.reduce_sum(tf.cast(ensemble_correct , dtype=tf.float32))
    ensemble_accuracy_final+=sess.run(ensemble_accuracy)
print("모델10개를 {}개씩 , 정확도 : {}".format(num1,ensemble_accuracy_final)) #  20190321 오류인듯



#학습
# for num1 in range(count_of_models):    
#     print(models[num1].build_graph)
#     print("======")
#     print(models[num1])
#     start_roof=0
#     increase_roof=100
#     finish_roof=100
#     batch_size=100
#     dataindex_len=len(x_data)  # 42000
#     traindataindex_len=int(dataindex_len/batch_size)  # 420
#     model_pt=["m1","m2","m3","m4""m5","m6""m7""m8""m9","m10"]
#     print("모델이름: model{}".format(num1))
#     for num2 in range(traindataindex_len):
#         batch_x = x_data[start_roof:finish_roof]
#         batch_y = y_data[start_roof:finish_roof]
#         model_pt[num1]=models[num1].train_model(batch_x , batch_y , keep_rate) # 앞수들 변수내용같은건 텐서플로 내에서 저장
#         start_roof=start_roof+increase_roof
#         finish_roof=finish_roof+increase_roof  
    
    
#     print("모델이름 : model{} , cost : {}".format(num1,model_pt[num1]))
    
    
    

#학습완료
    
###// 여기까지 완료    
    
# for num in range(count_of_models):
#     models[num].build_graph()
    
#     print(models[num])
    
#     start_roof=0
#     increase_roof=100
#     finish_roof=100
#     batch_size=100
#     dataindex_len=len(x_data)
#     traindataindex_len=int(dataindex_len/batch_size)
    
#     print(traindataindex_len)
#     H_zero = np.zeros((100,10),dtype=np.float32)
#     n=0
#     n1=100
#     n2=100
#     keep_rate=0.5
    
#     for step in range(10):

#         start_roof=0
#         increase_roof=100
#         finish_roof=100

#         for i in range(traindataindex_len):
#             batch_x = x_data[start_roof:finish_roof]
#             batch_y = y_data[start_roof:finish_roof]
#             models[num].train_model(batch_x , batch_y , keep_rate)
#             start_roof=start_roof+increase_roof
#             finish_roof=finish_roof+increase_roof

#         print("cost : {}".format(cost_val))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


ResourceExhaustedError: OOM when allocating tensor with shape[3136,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model9/model9/weight2/Adam_1/Assign (defined at <ipython-input-3-e603389f9ea9>:110)  = Assign[T=DT_FLOAT, _class=["loc:@model9/weight2/Assign"], _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model9/model9/weight2/Adam_1, model0/model0/weight2/Adam/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'model9/model9/weight2/Adam_1/Assign', defined at:
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\interactiveshell.py", line 2843, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\interactiveshell.py", line 2869, in _run_cell
    return runner(coro)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\interactiveshell.py", line 3044, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\interactiveshell.py", line 3209, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\IPython\core\interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-e603389f9ea9>", line 128, in <module>
    models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
  File "<ipython-input-3-e603389f9ea9>", line 128, in <listcomp>
    models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
  File "<ipython-input-3-e603389f9ea9>", line 67, in __init__
    self.build_graph()            # 해주고 안해주고 차이가 뭐지?
  File "<ipython-input-3-e603389f9ea9>", line 110, in build_graph
    self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\optimizer.py", line 410, in minimize
    name=name)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\optimizer.py", line 593, in apply_gradients
    self._create_slots(var_list)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\adam.py", line 136, in _create_slots
    self._zeros_slot(v, "v", self._name)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\optimizer.py", line 1139, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\slot_creator.py", line 183, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\slot_creator.py", line 157, in create_slot_with_initializer
    dtype)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\training\slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 922, in _get_single_variable
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 1329, in __init__
    constraint=constraint)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\variables.py", line 1481, in _init_from_args
    validate_shape=validate_shape).op
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\gpu_env\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3136,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model9/model9/weight2/Adam_1/Assign (defined at <ipython-input-3-e603389f9ea9>:110)  = Assign[T=DT_FLOAT, _class=["loc:@model9/weight2/Assign"], _grappler_relax_allocator_constraints=true, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model9/model9/weight2/Adam_1, model0/model0/weight2/Adam/Initializer/zeros)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.



In [31]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import warnings

## reset tensorflow graph
tf.reset_default_graph()



### x_data , y_data -> dataframe 형태
tf.reset_default_graph()

train = pd.read_csv("./data/mnist2/train.csv")
test = pd.read_csv("./data/mnist2/test.csv")


x_data=train.drop("label", axis=1, inplace=False)
train2=train["label"]

 
df1=pd.DataFrame()
arr = np.zeros((10,10), dtype=np.int32)
df1=arr
df2=pd.DataFrame()
for n in range(0,10):
    df1[n,n]=1
    df2[n]=np.arange(10)

tr2=int(len(train2))
for n in range(0,tr2):
    df2[n]=df1[train2[n]]
y_data=pd.DataFrame()
y_data=df2.transpose()

number=int(len(x_data)*2/3)

xtrain_data=x_data[0:number].values
xtext_data=x_data[number:-1].values

ytrain_data=y_data[0:number].values
ytest_data=y_data[number:-1].values
print("===============")
print(xtrain_data)
x_data=x_data.values
y_data=y_data.values


print("===============")

### x_data , y_data -> dataframe 형태 -> 넘파이 어레이가 공통적으로 쓰임
# display(x_data)
# print("============")
# display(y_data) #성공

#클레스 생성

class CNNModel: 
    
    def __init__(self,sess,name):     

        self.sess=sess
        self.name=name 
        self.build_graph()            # 해주고 안해주고 차이가 뭐지?
    def build_graph(self):
        with tf.variable_scope(self.name):
            self.X=tf.placeholder(shape=[None,784], dtype=tf.float32)
            self.Y=tf.placeholder(shape=[None,10], dtype=tf.float32)
            self.keep_rate=tf.placeholder(dtype=tf.float32) 
            
            X_img = tf.reshape(self.X, shape=[-1,28,28,1])

            W1=tf.Variable(tf.random_normal([5,5,1,32],stddev=0.01))

            L1 = tf.nn.conv2d(X_img,W1,strides=[1,1,1,1], padding="SAME")

            L1 = tf.nn.relu(L1)
            p1 = tf.nn.max_pool(L1 , ksize=[1,2,2,1] , strides=[1,2,2,1], padding="SAME")

            L2=tf.layers.conv2d(inputs=p1, filters=64, kernel_size=[5,5] , padding="SAME", strides=1 ,activation=tf.nn.relu)

            L2=tf.layers.max_pooling2d(inputs=L2 , pool_size=[2,2], padding="SAME" , strides=2)

            L2=tf.reshape(L2,shape=[-1,7*7*64])

            W2=tf.get_variable("weight2" , shape=[7*7*64,256], initializer=tf.contrib.layers.xavier_initializer())
            b2=tf.Variable(tf.random_normal([256]),name="bias2" )

            _layer1 = tf.nn.relu(tf.matmul(L2,W2)+b2 )
            layer1 = tf.nn.dropout(_layer1 , keep_prob=self.keep_rate)


            W3=tf.get_variable("weight3" , shape=[256,256], initializer=tf.contrib.layers.xavier_initializer())
            b3=tf.Variable(tf.random_normal([256]),name="bias3" )

            _layer2 = tf.nn.relu(tf.matmul(layer1,W3)+b3 )
            layer2 = tf.nn.dropout(_layer2 , keep_prob=self.keep_rate)


            W4=tf.get_variable("weight4" , shape=[256,10], initializer=tf.contrib.layers.xavier_initializer())
            b4=tf.Variable(tf.random_normal([10]),name="bias4" )

            self.H = tf.matmul(layer2,W4)+b4

            self.cost= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.H , labels=self.Y))

            self.train = tf.train.AdamOptimizer(learning_rate=0.000833).minimize(self.cost)

            self.predict = tf.argmax(self.H,1)
            self.correct=tf.equal(self.predict , tf.argmax(self.Y,1)) 

            self.accuracy=tf.reduce_sum(tf.cast(self.correct , dtype=tf.float32))


    def train_model(self,x,y,keep):
        
        _,cost_val=self.sess.run([self.train,self.cost], feed_dict={self.X:x , self.Y:y , self.keep_rate:keep})
        return cost_val
    
    def ensemble_predict(self,x,keep):
        H_val = self.sess.run(self.H, feed_dict={self.X:x,self.keep_rate:keep})
        return H_val
sess = tf.Session()
count_of_models = 10
models = [CNNModel(sess,"model"+ str(x)) for x in range(count_of_models)]
keep_rate=0.5


sess.run(tf.global_variables_initializer())
H_zero = np.zeros((100,10),dtype=np.float32)
print(H_zero)

#앙상블
    
for num1 in range(count_of_models):    
#     models[num1].build_graph
#     print("======")
#     print(models[num1])
    start_roof=0
    increase_roof=100
    finish_roof=100
    batch_size=100
    dataindex_len=len(x_data)  # 42000
    traindataindex_len=int(dataindex_len/batch_size)  # 420
    model_ensemble=["m0","m1","m2","m3","m4","m5","m6","m7","m8","m9"]
    
    H_zero = np.zeros((100,10),dtype=np.float32)
    print("모델이름: model{}".format(num1))
    for num2 in range(traindataindex_len):
        batch_x = x_data[start_roof:finish_roof]
        batch_y = y_data[start_roof:finish_roof]
        
        for num3 in range(0,9,1):
            models[num3].build_graph
            print(model_ensemble[num3])
            
            model_ensemble[num3]=(models[num3].ensemble_predict(batch_x , keep_rate)) # 앞수들 변수내용같은건 텐서플로 내에서 저장

            H_zero=H_zero+model_ensemble[num3]

        H_zero=H_zero/10    
        ensemble_predict = tf.argmax(H_zero,1)
        ensemble_correct=tf.equal(ensemble_predict , tf.argmax(batch_y,1)) 

        ensemble_accuracy=tf.reduce_sum(tf.cast(ensemble_correct , dtype=tf.float32))
        ensemble_accuracy=sess.run(ensemble_accuracy)
        start_roof=start_roof+increase_roof
        finish_roof=finish_roof+increase_roof  
        print("모델10개를 {}번씩 , 정확도 : {}".format(num2,ensemble_accuracy))
        


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.

AttributeError: 'str' object has no attribute 'append'

In [30]:
len(model_ensemble[num3])

IndexError: list index out of range